// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/service/cart/v1/cart.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CartInfoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	GoodsId       int64                  `protobuf:"varint,3,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	GoodsSn       string                 `protobuf:"bytes,4,opt,name=goodsSn,proto3" json:"goodsSn,omitempty"`
	GoodsName     string                 `protobuf:"bytes,5,opt,name=goodsName,proto3" json:"goodsName,omitempty"`
	SkuId         int64                  `protobuf:"varint,6,opt,name=skuId,proto3" json:"skuId,omitempty"`
	GoodsPrice    int64                  `protobuf:"varint,7,opt,name=goodsPrice,proto3" json:"goodsPrice,omitempty"`
	GoodsNum      int32                  `protobuf:"varint,8,opt,name=goodsNum,proto3" json:"goodsNum,omitempty"`
	IsSelect      bool                   `protobuf:"varint,9,opt,name=isSelect,proto3" json:"isSelect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartInfoReply) Reset() {
	*x = CartInfoReply{}
	mi := &file_api_service_cart_v1_cart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartInfoReply) ProtoMessage() {}

func (x *CartInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_cart_v1_cart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartInfoReply.ProtoReflect.Descriptor instead.
func (*CartInfoReply) Descriptor() ([]byte, []int) {
	return file_api_service_cart_v1_cart_proto_rawDescGZIP(), []int{0}
}

func (x *CartInfoReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CartInfoReply) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CartInfoReply) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *CartInfoReply) GetGoodsSn() string {
	if x != nil {
		return x.GoodsSn
	}
	return ""
}

func (x *CartInfoReply) GetGoodsName() string {
	if x != nil {
		return x.GoodsName
	}
	return ""
}

func (x *CartInfoReply) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *CartInfoReply) GetGoodsPrice() int64 {
	if x != nil {
		return x.GoodsPrice
	}
	return 0
}

func (x *CartInfoReply) GetGoodsNum() int32 {
	if x != nil {
		return x.GoodsNum
	}
	return 0
}

func (x *CartInfoReply) GetIsSelect() bool {
	if x != nil {
		return x.IsSelect
	}
	return false
}

type CreateCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	GoodsId       int64                  `protobuf:"varint,3,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	GoodsSn       string                 `protobuf:"bytes,4,opt,name=goodsSn,proto3" json:"goodsSn,omitempty"`
	GoodsName     string                 `protobuf:"bytes,5,opt,name=goodsName,proto3" json:"goodsName,omitempty"`
	SkuId         int64                  `protobuf:"varint,6,opt,name=skuId,proto3" json:"skuId,omitempty"`
	GoodsPrice    int64                  `protobuf:"varint,7,opt,name=goodsPrice,proto3" json:"goodsPrice,omitempty"`
	GoodsNum      int32                  `protobuf:"varint,8,opt,name=goodsNum,proto3" json:"goodsNum,omitempty"`
	IsSelect      bool                   `protobuf:"varint,9,opt,name=isSelect,proto3" json:"isSelect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCartRequest) Reset() {
	*x = CreateCartRequest{}
	mi := &file_api_service_cart_v1_cart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCartRequest) ProtoMessage() {}

func (x *CreateCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_cart_v1_cart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCartRequest.ProtoReflect.Descriptor instead.
func (*CreateCartRequest) Descriptor() ([]byte, []int) {
	return file_api_service_cart_v1_cart_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCartRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateCartRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateCartRequest) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *CreateCartRequest) GetGoodsSn() string {
	if x != nil {
		return x.GoodsSn
	}
	return ""
}

func (x *CreateCartRequest) GetGoodsName() string {
	if x != nil {
		return x.GoodsName
	}
	return ""
}

func (x *CreateCartRequest) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *CreateCartRequest) GetGoodsPrice() int64 {
	if x != nil {
		return x.GoodsPrice
	}
	return 0
}

func (x *CreateCartRequest) GetGoodsNum() int32 {
	if x != nil {
		return x.GoodsNum
	}
	return 0
}

func (x *CreateCartRequest) GetIsSelect() bool {
	if x != nil {
		return x.IsSelect
	}
	return false
}

type UpdateCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	GoodsNum      int32                  `protobuf:"varint,3,opt,name=goodsNum,proto3" json:"goodsNum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCartRequest) Reset() {
	*x = UpdateCartRequest{}
	mi := &file_api_service_cart_v1_cart_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCartRequest) ProtoMessage() {}

func (x *UpdateCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_cart_v1_cart_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCartRequest.ProtoReflect.Descriptor instead.
func (*UpdateCartRequest) Descriptor() ([]byte, []int) {
	return file_api_service_cart_v1_cart_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateCartRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCartRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateCartRequest) GetGoodsNum() int32 {
	if x != nil {
		return x.GoodsNum
	}
	return 0
}

type UpdateCartReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCartReply) Reset() {
	*x = UpdateCartReply{}
	mi := &file_api_service_cart_v1_cart_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCartReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCartReply) ProtoMessage() {}

func (x *UpdateCartReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_cart_v1_cart_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCartReply.ProtoReflect.Descriptor instead.
func (*UpdateCartReply) Descriptor() ([]byte, []int) {
	return file_api_service_cart_v1_cart_proto_rawDescGZIP(), []int{3}
}

type CheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_api_service_cart_v1_cart_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_cart_v1_cart_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_api_service_cart_v1_cart_proto_rawDescGZIP(), []int{4}
}

func (x *CheckResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCartRequest) Reset() {
	*x = DeleteCartRequest{}
	mi := &file_api_service_cart_v1_cart_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCartRequest) ProtoMessage() {}

func (x *DeleteCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_cart_v1_cart_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCartRequest.ProtoReflect.Descriptor instead.
func (*DeleteCartRequest) Descriptor() ([]byte, []int) {
	return file_api_service_cart_v1_cart_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCartRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteCartRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteCartReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCartReply) Reset() {
	*x = DeleteCartReply{}
	mi := &file_api_service_cart_v1_cart_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCartReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCartReply) ProtoMessage() {}

func (x *DeleteCartReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_cart_v1_cart_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCartReply.ProtoReflect.Descriptor instead.
func (*DeleteCartReply) Descriptor() ([]byte, []int) {
	return file_api_service_cart_v1_cart_proto_rawDescGZIP(), []int{6}
}

type GetCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartRequest) Reset() {
	*x = GetCartRequest{}
	mi := &file_api_service_cart_v1_cart_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartRequest) ProtoMessage() {}

func (x *GetCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_cart_v1_cart_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartRequest.ProtoReflect.Descriptor instead.
func (*GetCartRequest) Descriptor() ([]byte, []int) {
	return file_api_service_cart_v1_cart_proto_rawDescGZIP(), []int{7}
}

func (x *GetCartRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetCartRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetCartReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *CartInfoReply         `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartReply) Reset() {
	*x = GetCartReply{}
	mi := &file_api_service_cart_v1_cart_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartReply) ProtoMessage() {}

func (x *GetCartReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_cart_v1_cart_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartReply.ProtoReflect.Descriptor instead.
func (*GetCartReply) Descriptor() ([]byte, []int) {
	return file_api_service_cart_v1_cart_proto_rawDescGZIP(), []int{8}
}

func (x *GetCartReply) GetInfo() *CartInfoReply {
	if x != nil {
		return x.Info
	}
	return nil
}

type ListCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCartRequest) Reset() {
	*x = ListCartRequest{}
	mi := &file_api_service_cart_v1_cart_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCartRequest) ProtoMessage() {}

func (x *ListCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_cart_v1_cart_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCartRequest.ProtoReflect.Descriptor instead.
func (*ListCartRequest) Descriptor() ([]byte, []int) {
	return file_api_service_cart_v1_cart_proto_rawDescGZIP(), []int{9}
}

func (x *ListCartRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CartListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*CartInfoReply       `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartListReply) Reset() {
	*x = CartListReply{}
	mi := &file_api_service_cart_v1_cart_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartListReply) ProtoMessage() {}

func (x *CartListReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_cart_v1_cart_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartListReply.ProtoReflect.Descriptor instead.
func (*CartListReply) Descriptor() ([]byte, []int) {
	return file_api_service_cart_v1_cart_proto_rawDescGZIP(), []int{10}
}

func (x *CartListReply) GetResults() []*CartInfoReply {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_api_service_cart_v1_cart_proto protoreflect.FileDescriptor

const file_api_service_cart_v1_cart_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/service/cart/v1/cart.proto\x12\acart.v1\x1a\x17validate/validate.proto\"\xf7\x01\n" +
	"\rCartInfoReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x18\n" +
	"\agoodsId\x18\x03 \x01(\x03R\agoodsId\x12\x18\n" +
	"\agoodsSn\x18\x04 \x01(\tR\agoodsSn\x12\x1c\n" +
	"\tgoodsName\x18\x05 \x01(\tR\tgoodsName\x12\x14\n" +
	"\x05skuId\x18\x06 \x01(\x03R\x05skuId\x12\x1e\n" +
	"\n" +
	"goodsPrice\x18\a \x01(\x03R\n" +
	"goodsPrice\x12\x1a\n" +
	"\bgoodsNum\x18\b \x01(\x05R\bgoodsNum\x12\x1a\n" +
	"\bisSelect\x18\t \x01(\bR\bisSelect\"\xc3\x02\n" +
	"\x11CreateCartRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\x06userId\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06userId\x12!\n" +
	"\agoodsId\x18\x03 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\agoodsId\x12!\n" +
	"\agoodsSn\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\agoodsSn\x12%\n" +
	"\tgoodsName\x18\x05 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\tgoodsName\x12\x1d\n" +
	"\x05skuId\x18\x06 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x05skuId\x12'\n" +
	"\n" +
	"goodsPrice\x18\a \x01(\x03B\a\xfaB\x04\"\x02 \x00R\n" +
	"goodsPrice\x12#\n" +
	"\bgoodsNum\x18\b \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\bgoodsNum\x12#\n" +
	"\bisSelect\x18\t \x01(\bB\a\xfaB\x04j\x02\b\x01R\bisSelect\"W\n" +
	"\x11UpdateCartRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bgoodsNum\x18\x03 \x01(\x05R\bgoodsNum\"\x11\n" +
	"\x0fUpdateCartReply\")\n" +
	"\rCheckResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\";\n" +
	"\x11DeleteCartRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\"\x11\n" +
	"\x0fDeleteCartReply\"8\n" +
	"\x0eGetCartRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\":\n" +
	"\fGetCartReply\x12*\n" +
	"\x04info\x18\x01 \x01(\v2\x16.cart.v1.CartInfoReplyR\x04info\")\n" +
	"\x0fListCartRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\"A\n" +
	"\rCartListReply\x120\n" +
	"\aresults\x18\x01 \x03(\v2\x16.cart.v1.CartInfoReplyR\aresults2\xc5\x02\n" +
	"\x04Cart\x12@\n" +
	"\n" +
	"CreateCart\x12\x1a.cart.v1.CreateCartRequest\x1a\x16.cart.v1.CartInfoReply\x12@\n" +
	"\n" +
	"UpdateCart\x12\x1a.cart.v1.UpdateCartRequest\x1a\x16.cart.v1.CheckResponse\x12@\n" +
	"\n" +
	"DeleteCart\x12\x1a.cart.v1.DeleteCartRequest\x1a\x16.cart.v1.CheckResponse\x129\n" +
	"\aGetCart\x12\x17.cart.v1.GetCartRequest\x1a\x15.cart.v1.GetCartReply\x12<\n" +
	"\bListCart\x12\x18.cart.v1.ListCartRequest\x1a\x16.cart.v1.CartListReplyB\x15Z\x13cart/api/cart/v1;v1b\x06proto3"

var (
	file_api_service_cart_v1_cart_proto_rawDescOnce sync.Once
	file_api_service_cart_v1_cart_proto_rawDescData []byte
)

func file_api_service_cart_v1_cart_proto_rawDescGZIP() []byte {
	file_api_service_cart_v1_cart_proto_rawDescOnce.Do(func() {
		file_api_service_cart_v1_cart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_service_cart_v1_cart_proto_rawDesc), len(file_api_service_cart_v1_cart_proto_rawDesc)))
	})
	return file_api_service_cart_v1_cart_proto_rawDescData
}

var file_api_service_cart_v1_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_service_cart_v1_cart_proto_goTypes = []any{
	(*CartInfoReply)(nil),     // 0: cart.v1.CartInfoReply
	(*CreateCartRequest)(nil), // 1: cart.v1.CreateCartRequest
	(*UpdateCartRequest)(nil), // 2: cart.v1.UpdateCartRequest
	(*UpdateCartReply)(nil),   // 3: cart.v1.UpdateCartReply
	(*CheckResponse)(nil),     // 4: cart.v1.CheckResponse
	(*DeleteCartRequest)(nil), // 5: cart.v1.DeleteCartRequest
	(*DeleteCartReply)(nil),   // 6: cart.v1.DeleteCartReply
	(*GetCartRequest)(nil),    // 7: cart.v1.GetCartRequest
	(*GetCartReply)(nil),      // 8: cart.v1.GetCartReply
	(*ListCartRequest)(nil),   // 9: cart.v1.ListCartRequest
	(*CartListReply)(nil),     // 10: cart.v1.CartListReply
}
var file_api_service_cart_v1_cart_proto_depIdxs = []int32{
	0,  // 0: cart.v1.GetCartReply.info:type_name -> cart.v1.CartInfoReply
	0,  // 1: cart.v1.CartListReply.results:type_name -> cart.v1.CartInfoReply
	1,  // 2: cart.v1.Cart.CreateCart:input_type -> cart.v1.CreateCartRequest
	2,  // 3: cart.v1.Cart.UpdateCart:input_type -> cart.v1.UpdateCartRequest
	5,  // 4: cart.v1.Cart.DeleteCart:input_type -> cart.v1.DeleteCartRequest
	7,  // 5: cart.v1.Cart.GetCart:input_type -> cart.v1.GetCartRequest
	9,  // 6: cart.v1.Cart.ListCart:input_type -> cart.v1.ListCartRequest
	0,  // 7: cart.v1.Cart.CreateCart:output_type -> cart.v1.CartInfoReply
	4,  // 8: cart.v1.Cart.UpdateCart:output_type -> cart.v1.CheckResponse
	4,  // 9: cart.v1.Cart.DeleteCart:output_type -> cart.v1.CheckResponse
	8,  // 10: cart.v1.Cart.GetCart:output_type -> cart.v1.GetCartReply
	10, // 11: cart.v1.Cart.ListCart:output_type -> cart.v1.CartListReply
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_service_cart_v1_cart_proto_init() }
func file_api_service_cart_v1_cart_proto_init() {
	if File_api_service_cart_v1_cart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_service_cart_v1_cart_proto_rawDesc), len(file_api_service_cart_v1_cart_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_service_cart_v1_cart_proto_goTypes,
		DependencyIndexes: file_api_service_cart_v1_cart_proto_depIdxs,
		MessageInfos:      file_api_service_cart_v1_cart_proto_msgTypes,
	}.Build()
	File_api_service_cart_v1_cart_proto = out.File
	file_api_service_cart_v1_cart_proto_goTypes = nil
	file_api_service_cart_v1_cart_proto_depIdxs = nil
}
