// Code generated by Wire. DO NOT EDIT.

//go:build !wireinject
// +build !wireinject

package main

import (
	"payment/internal/biz"
	"payment/internal/conf"
	"payment/internal/data"
	"payment/internal/server"
	"payment/internal/service"

	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

func initApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, confService *conf.Service, mq *conf.Mq, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData)
	discovery := data.NewDiscovery(registry)
	orderClient := data.NewOrderServiceClient(confService, discovery)
	dataData, cleanup, err := data.NewData(confData, logger, db, orderClient)
	if err != nil {
		return nil, nil, err
	}
	paymentRepo := data.NewPaymentRepo(dataData, logger)
	paymentUsecase := biz.NewPaymentUsecase(paymentRepo, logger)
	paymentService := service.NewPaymentService(paymentUsecase, orderClient, mq, logger)
	grpcServer := server.NewGRPCServer(confServer, paymentService, logger)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, grpcServer, registrar)
	return app, cleanup, nil
}
