// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/service/payment/v1/payment.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	OrderSn       string                 `protobuf:"bytes,2,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Channel       string                 `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_api_service_payment_v1_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_payment_v1_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_api_service_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePaymentRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreatePaymentRequest) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *CreatePaymentRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePaymentRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

type PaymentInfoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PaymentNo     string                 `protobuf:"bytes,2,opt,name=paymentNo,proto3" json:"paymentNo,omitempty"`
	OrderSn       string                 `protobuf:"bytes,3,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Channel       string                 `protobuf:"bytes,5,opt,name=channel,proto3" json:"channel,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentInfoReply) Reset() {
	*x = PaymentInfoReply{}
	mi := &file_api_service_payment_v1_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentInfoReply) ProtoMessage() {}

func (x *PaymentInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_payment_v1_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentInfoReply.ProtoReflect.Descriptor instead.
func (*PaymentInfoReply) Descriptor() ([]byte, []int) {
	return file_api_service_payment_v1_payment_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentInfoReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PaymentInfoReply) GetPaymentNo() string {
	if x != nil {
		return x.PaymentNo
	}
	return ""
}

func (x *PaymentInfoReply) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *PaymentInfoReply) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentInfoReply) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *PaymentInfoReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type PaymentCallbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentNo     string                 `protobuf:"bytes,1,opt,name=paymentNo,proto3" json:"paymentNo,omitempty"`
	TradeNo       string                 `protobuf:"bytes,2,opt,name=tradeNo,proto3" json:"tradeNo,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentCallbackRequest) Reset() {
	*x = PaymentCallbackRequest{}
	mi := &file_api_service_payment_v1_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentCallbackRequest) ProtoMessage() {}

func (x *PaymentCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_payment_v1_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentCallbackRequest.ProtoReflect.Descriptor instead.
func (*PaymentCallbackRequest) Descriptor() ([]byte, []int) {
	return file_api_service_payment_v1_payment_proto_rawDescGZIP(), []int{2}
}

func (x *PaymentCallbackRequest) GetPaymentNo() string {
	if x != nil {
		return x.PaymentNo
	}
	return ""
}

func (x *PaymentCallbackRequest) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *PaymentCallbackRequest) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CheckReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckReply) Reset() {
	*x = CheckReply{}
	mi := &file_api_service_payment_v1_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckReply) ProtoMessage() {}

func (x *CheckReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_payment_v1_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckReply.ProtoReflect.Descriptor instead.
func (*CheckReply) Descriptor() ([]byte, []int) {
	return file_api_service_payment_v1_payment_proto_rawDescGZIP(), []int{3}
}

func (x *CheckReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CheckReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_service_payment_v1_payment_proto protoreflect.FileDescriptor

const file_api_service_payment_v1_payment_proto_rawDesc = "" +
	"\n" +
	"$api/service/payment/v1/payment.proto\x12\n" +
	"payment.v1\"z\n" +
	"\x14CreatePaymentRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x18\n" +
	"\aorderSn\x18\x02 \x01(\tR\aorderSn\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x18\n" +
	"\achannel\x18\x04 \x01(\tR\achannel\"\xa4\x01\n" +
	"\x10PaymentInfoReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\tpaymentNo\x18\x02 \x01(\tR\tpaymentNo\x12\x18\n" +
	"\aorderSn\x18\x03 \x01(\tR\aorderSn\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x18\n" +
	"\achannel\x18\x05 \x01(\tR\achannel\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\"j\n" +
	"\x16PaymentCallbackRequest\x12\x1c\n" +
	"\tpaymentNo\x18\x01 \x01(\tR\tpaymentNo\x12\x18\n" +
	"\atradeNo\x18\x02 \x01(\tR\atradeNo\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"@\n" +
	"\n" +
	"CheckReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xa9\x01\n" +
	"\aPayment\x12O\n" +
	"\rCreatePayment\x12 .payment.v1.CreatePaymentRequest\x1a\x1c.payment.v1.PaymentInfoReply\x12M\n" +
	"\x0fPaymentCallback\x12\".payment.v1.PaymentCallbackRequest\x1a\x16.payment.v1.CheckReplyB\x1bZ\x19payment/api/payment/v1;v1b\x06proto3"

var (
	file_api_service_payment_v1_payment_proto_rawDescOnce sync.Once
	file_api_service_payment_v1_payment_proto_rawDescData []byte
)

func file_api_service_payment_v1_payment_proto_rawDescGZIP() []byte {
	file_api_service_payment_v1_payment_proto_rawDescOnce.Do(func() {
		file_api_service_payment_v1_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_service_payment_v1_payment_proto_rawDesc), len(file_api_service_payment_v1_payment_proto_rawDesc)))
	})
	return file_api_service_payment_v1_payment_proto_rawDescData
}

var file_api_service_payment_v1_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_service_payment_v1_payment_proto_goTypes = []any{
	(*CreatePaymentRequest)(nil),   // 0: payment.v1.CreatePaymentRequest
	(*PaymentInfoReply)(nil),       // 1: payment.v1.PaymentInfoReply
	(*PaymentCallbackRequest)(nil), // 2: payment.v1.PaymentCallbackRequest
	(*CheckReply)(nil),             // 3: payment.v1.CheckReply
}
var file_api_service_payment_v1_payment_proto_depIdxs = []int32{
	0, // 0: payment.v1.Payment.CreatePayment:input_type -> payment.v1.CreatePaymentRequest
	2, // 1: payment.v1.Payment.PaymentCallback:input_type -> payment.v1.PaymentCallbackRequest
	1, // 2: payment.v1.Payment.CreatePayment:output_type -> payment.v1.PaymentInfoReply
	3, // 3: payment.v1.Payment.PaymentCallback:output_type -> payment.v1.CheckReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_service_payment_v1_payment_proto_init() }
func file_api_service_payment_v1_payment_proto_init() {
	if File_api_service_payment_v1_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_service_payment_v1_payment_proto_rawDesc), len(file_api_service_payment_v1_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_service_payment_v1_payment_proto_goTypes,
		DependencyIndexes: file_api_service_payment_v1_payment_proto_depIdxs,
		MessageInfos:      file_api_service_payment_v1_payment_proto_msgTypes,
	}.Build()
	File_api_service_payment_v1_payment_proto = out.File
	file_api_service_payment_v1_payment_proto_goTypes = nil
	file_api_service_payment_v1_payment_proto_depIdxs = nil
}
