// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/service/payment/v1/payment.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CreatePaymentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreatePaymentRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreatePaymentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreatePaymentRequestMultiError, or nil if none found.
func (m *CreatePaymentRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreatePaymentRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for OrderSn

	// no validation rules for Amount

	// no validation rules for Channel

	if len(errors) > 0 {
		return CreatePaymentRequestMultiError(errors)
	}

	return nil
}

// CreatePaymentRequestMultiError is an error wrapping multiple validation
// errors returned by CreatePaymentRequest.ValidateAll() if the designated
// constraints aren't met.
type CreatePaymentRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreatePaymentRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreatePaymentRequestMultiError) AllErrors() []error { return m }

// CreatePaymentRequestValidationError is the validation error returned by
// CreatePaymentRequest.Validate if the designated constraints aren't met.
type CreatePaymentRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreatePaymentRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreatePaymentRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreatePaymentRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreatePaymentRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreatePaymentRequestValidationError) ErrorName() string {
	return "CreatePaymentRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreatePaymentRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreatePaymentRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreatePaymentRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreatePaymentRequestValidationError{}

// Validate checks the field values on PaymentInfoReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *PaymentInfoReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PaymentInfoReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PaymentInfoReplyMultiError, or nil if none found.
func (m *PaymentInfoReply) ValidateAll() error {
	return m.validate(true)
}

func (m *PaymentInfoReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for PaymentNo

	// no validation rules for OrderSn

	// no validation rules for Amount

	// no validation rules for Channel

	// no validation rules for Status

	if len(errors) > 0 {
		return PaymentInfoReplyMultiError(errors)
	}

	return nil
}

// PaymentInfoReplyMultiError is an error wrapping multiple validation errors
// returned by PaymentInfoReply.ValidateAll() if the designated constraints
// aren't met.
type PaymentInfoReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PaymentInfoReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PaymentInfoReplyMultiError) AllErrors() []error { return m }

// PaymentInfoReplyValidationError is the validation error returned by
// PaymentInfoReply.Validate if the designated constraints aren't met.
type PaymentInfoReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PaymentInfoReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PaymentInfoReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PaymentInfoReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PaymentInfoReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PaymentInfoReplyValidationError) ErrorName() string { return "PaymentInfoReplyValidationError" }

// Error satisfies the builtin error interface
func (e PaymentInfoReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPaymentInfoReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PaymentInfoReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PaymentInfoReplyValidationError{}

// Validate checks the field values on PaymentCallbackRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PaymentCallbackRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PaymentCallbackRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PaymentCallbackRequestMultiError, or nil if none found.
func (m *PaymentCallbackRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PaymentCallbackRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PaymentNo

	// no validation rules for TradeNo

	// no validation rules for Success

	if len(errors) > 0 {
		return PaymentCallbackRequestMultiError(errors)
	}

	return nil
}

// PaymentCallbackRequestMultiError is an error wrapping multiple validation
// errors returned by PaymentCallbackRequest.ValidateAll() if the designated
// constraints aren't met.
type PaymentCallbackRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PaymentCallbackRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PaymentCallbackRequestMultiError) AllErrors() []error { return m }

// PaymentCallbackRequestValidationError is the validation error returned by
// PaymentCallbackRequest.Validate if the designated constraints aren't met.
type PaymentCallbackRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PaymentCallbackRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PaymentCallbackRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PaymentCallbackRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PaymentCallbackRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PaymentCallbackRequestValidationError) ErrorName() string {
	return "PaymentCallbackRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PaymentCallbackRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPaymentCallbackRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PaymentCallbackRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PaymentCallbackRequestValidationError{}

// Validate checks the field values on CheckReply with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CheckReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CheckReply with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CheckReplyMultiError, or
// nil if none found.
func (m *CheckReply) ValidateAll() error {
	return m.validate(true)
}

func (m *CheckReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	// no validation rules for Message

	if len(errors) > 0 {
		return CheckReplyMultiError(errors)
	}

	return nil
}

// CheckReplyMultiError is an error wrapping multiple validation errors
// returned by CheckReply.ValidateAll() if the designated constraints aren't met.
type CheckReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CheckReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CheckReplyMultiError) AllErrors() []error { return m }

// CheckReplyValidationError is the validation error returned by
// CheckReply.Validate if the designated constraints aren't met.
type CheckReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CheckReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CheckReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CheckReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CheckReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CheckReplyValidationError) ErrorName() string { return "CheckReplyValidationError" }

// Error satisfies the builtin error interface
func (e CheckReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCheckReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CheckReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CheckReplyValidationError{}
