// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"admin/internal/biz"
	"admin/internal/conf"
	"admin/internal/data"
	"admin/internal/server"
	"admin/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init admin application.
func initApp(confServer *conf.Server, confData *conf.Data, auth *conf.Auth, confService *conf.Service, registry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	discovery := data.NewDiscovery(registry)
	userClient := data.NewUserServiceClient(auth, confService, discovery)
	goodsClient := data.NewGoodsServiceClient(auth, confService, discovery)
	orderClient := data.NewOrderServiceClient(auth, confService, discovery)
	db := data.NewDB(confData)
	dataData, err := data.NewData(confData, db, userClient, goodsClient, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userUsecase := biz.NewUserUsecase(userRepo, logger, auth)
	addressRepo := data.NewAddressRepo(dataData, logger)
	addressUsecase := biz.NewAddressUsecase(userRepo, addressRepo, logger, auth)
	goodsUsecase := biz.NewGoodsUsecase(goodsClient, logger)
	orderUsecase := biz.NewOrderUsecase(orderClient, logger)
	permissionRepo := data.NewPermissionRepo(dataData, logger)
	permissionUsecase := biz.NewPermissionUsecase(permissionRepo, logger)
	adminService := service.NewAdminService(userUsecase, addressUsecase, goodsUsecase, orderUsecase, permissionUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, auth, adminService, logger)
	registrar := data.NewRegistrar(registry)
	app := newApp(logger, httpServer, registrar)
	return app, func() {
	}, nil
}
