// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: inventory/v1/inventory.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Inventory_QueryStock_FullMethodName    = "/inventory.v1.Inventory/QueryStock"
	Inventory_TryLock_FullMethodName       = "/inventory.v1.Inventory/TryLock"
	Inventory_ConfirmDeduct_FullMethodName = "/inventory.v1.Inventory/ConfirmDeduct"
	Inventory_Release_FullMethodName       = "/inventory.v1.Inventory/Release"
)

// InventoryClient is the client API for Inventory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InventoryClient interface {
	QueryStock(ctx context.Context, in *StockQueryRequest, opts ...grpc.CallOption) (*StockQueryReply, error)
	TryLock(ctx context.Context, in *TryLockRequest, opts ...grpc.CallOption) (*TryLockReply, error)
	ConfirmDeduct(ctx context.Context, in *ConfirmDeductRequest, opts ...grpc.CallOption) (*CheckReply, error)
	Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*CheckReply, error)
}

type inventoryClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryClient(cc grpc.ClientConnInterface) InventoryClient {
	return &inventoryClient{cc}
}

func (c *inventoryClient) QueryStock(ctx context.Context, in *StockQueryRequest, opts ...grpc.CallOption) (*StockQueryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StockQueryReply)
	err := c.cc.Invoke(ctx, Inventory_QueryStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryClient) TryLock(ctx context.Context, in *TryLockRequest, opts ...grpc.CallOption) (*TryLockReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TryLockReply)
	err := c.cc.Invoke(ctx, Inventory_TryLock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryClient) ConfirmDeduct(ctx context.Context, in *ConfirmDeductRequest, opts ...grpc.CallOption) (*CheckReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckReply)
	err := c.cc.Invoke(ctx, Inventory_ConfirmDeduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryClient) Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*CheckReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckReply)
	err := c.cc.Invoke(ctx, Inventory_Release_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryServer is the server API for Inventory service.
// All implementations must embed UnimplementedInventoryServer
// for forward compatibility.
type InventoryServer interface {
	QueryStock(context.Context, *StockQueryRequest) (*StockQueryReply, error)
	TryLock(context.Context, *TryLockRequest) (*TryLockReply, error)
	ConfirmDeduct(context.Context, *ConfirmDeductRequest) (*CheckReply, error)
	Release(context.Context, *ReleaseRequest) (*CheckReply, error)
	mustEmbedUnimplementedInventoryServer()
}

// UnimplementedInventoryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInventoryServer struct{}

func (UnimplementedInventoryServer) QueryStock(context.Context, *StockQueryRequest) (*StockQueryReply, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryStock not implemented")
}
func (UnimplementedInventoryServer) TryLock(context.Context, *TryLockRequest) (*TryLockReply, error) {
	return nil, status.Error(codes.Unimplemented, "method TryLock not implemented")
}
func (UnimplementedInventoryServer) ConfirmDeduct(context.Context, *ConfirmDeductRequest) (*CheckReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmDeduct not implemented")
}
func (UnimplementedInventoryServer) Release(context.Context, *ReleaseRequest) (*CheckReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Release not implemented")
}
func (UnimplementedInventoryServer) mustEmbedUnimplementedInventoryServer() {}
func (UnimplementedInventoryServer) testEmbeddedByValue()                   {}

// UnsafeInventoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryServer will
// result in compilation errors.
type UnsafeInventoryServer interface {
	mustEmbedUnimplementedInventoryServer()
}

func RegisterInventoryServer(s grpc.ServiceRegistrar, srv InventoryServer) {
	// If the following call panics, it indicates UnimplementedInventoryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Inventory_ServiceDesc, srv)
}

func _Inventory_QueryStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).QueryStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Inventory_QueryStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).QueryStock(ctx, req.(*StockQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inventory_TryLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TryLockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).TryLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Inventory_TryLock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).TryLock(ctx, req.(*TryLockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inventory_ConfirmDeduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmDeductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).ConfirmDeduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Inventory_ConfirmDeduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).ConfirmDeduct(ctx, req.(*ConfirmDeductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inventory_Release_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).Release(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Inventory_Release_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).Release(ctx, req.(*ReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Inventory_ServiceDesc is the grpc.ServiceDesc for Inventory service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Inventory_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inventory.v1.Inventory",
	HandlerType: (*InventoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryStock",
			Handler:    _Inventory_QueryStock_Handler,
		},
		{
			MethodName: "TryLock",
			Handler:    _Inventory_TryLock_Handler,
		},
		{
			MethodName: "ConfirmDeduct",
			Handler:    _Inventory_ConfirmDeduct_Handler,
		},
		{
			MethodName: "Release",
			Handler:    _Inventory_Release_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inventory/v1/inventory.proto",
}
