server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:50052
    timeout: 1s
data:
  database:
    driver: postgres
    source: postgres://postgres:root@127.0.0.1:5432/shop_goods?sslmode=disable&TimeZone=Asia/Shanghai
  redis:
    addr: 127.0.0.1:6379
    password: root
    dial_timeout: 1s
    read_timeout: 0.2s
    write_timeout: 0.2s
  elastic:
    addr: http://127.0.0.1:9200
trace:
  endpoint: http://127.0.0.1:14268/api/traces
mq:
  addr: amqp://root:root@127.0.0.1:5672/
service:
  inventory:
    endpoint: discovery:///shop.inventory.service
