// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: inventory/v1/inventory.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StockItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuId         int64                  `protobuf:"varint,1,opt,name=skuId,proto3" json:"skuId,omitempty"`
	Inventory     int64                  `protobuf:"varint,2,opt,name=inventory,proto3" json:"inventory,omitempty"`
	Locked        int64                  `protobuf:"varint,3,opt,name=locked,proto3" json:"locked,omitempty"`
	Available     int64                  `protobuf:"varint,4,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockItem) Reset() {
	*x = StockItem{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockItem) ProtoMessage() {}

func (x *StockItem) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockItem.ProtoReflect.Descriptor instead.
func (*StockItem) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *StockItem) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *StockItem) GetInventory() int64 {
	if x != nil {
		return x.Inventory
	}
	return 0
}

func (x *StockItem) GetLocked() int64 {
	if x != nil {
		return x.Locked
	}
	return 0
}

func (x *StockItem) GetAvailable() int64 {
	if x != nil {
		return x.Available
	}
	return 0
}

type StockQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuIds        []int64                `protobuf:"varint,1,rep,packed,name=skuIds,proto3" json:"skuIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockQueryRequest) Reset() {
	*x = StockQueryRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockQueryRequest) ProtoMessage() {}

func (x *StockQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockQueryRequest.ProtoReflect.Descriptor instead.
func (*StockQueryRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *StockQueryRequest) GetSkuIds() []int64 {
	if x != nil {
		return x.SkuIds
	}
	return nil
}

type StockQueryReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*StockItem           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockQueryReply) Reset() {
	*x = StockQueryReply{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockQueryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockQueryReply) ProtoMessage() {}

func (x *StockQueryReply) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockQueryReply.ProtoReflect.Descriptor instead.
func (*StockQueryReply) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *StockQueryReply) GetItems() []*StockItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type SkuItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuId         int64                  `protobuf:"varint,1,opt,name=skuId,proto3" json:"skuId,omitempty"`
	Num           int32                  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkuItem) Reset() {
	*x = SkuItem{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkuItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkuItem) ProtoMessage() {}

func (x *SkuItem) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkuItem.ProtoReflect.Descriptor instead.
func (*SkuItem) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *SkuItem) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *SkuItem) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type TryLockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderSn       string                 `protobuf:"bytes,1,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	Items         []*SkuItem             `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TryLockRequest) Reset() {
	*x = TryLockRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TryLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TryLockRequest) ProtoMessage() {}

func (x *TryLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TryLockRequest.ProtoReflect.Descriptor instead.
func (*TryLockRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *TryLockRequest) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *TryLockRequest) GetItems() []*SkuItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type TryLockReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TryLockReply) Reset() {
	*x = TryLockReply{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TryLockReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TryLockReply) ProtoMessage() {}

func (x *TryLockReply) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TryLockReply.ProtoReflect.Descriptor instead.
func (*TryLockReply) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *TryLockReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TryLockReply) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ConfirmDeductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderSn       string                 `protobuf:"bytes,1,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	Items         []*SkuItem             `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmDeductRequest) Reset() {
	*x = ConfirmDeductRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmDeductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmDeductRequest) ProtoMessage() {}

func (x *ConfirmDeductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmDeductRequest.ProtoReflect.Descriptor instead.
func (*ConfirmDeductRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *ConfirmDeductRequest) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *ConfirmDeductRequest) GetItems() []*SkuItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderSn       string                 `protobuf:"bytes,1,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	Items         []*SkuItem             `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseRequest) Reset() {
	*x = ReleaseRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRequest) ProtoMessage() {}

func (x *ReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRequest.ProtoReflect.Descriptor instead.
func (*ReleaseRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *ReleaseRequest) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *ReleaseRequest) GetItems() []*SkuItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CheckReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckReply) Reset() {
	*x = CheckReply{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckReply) ProtoMessage() {}

func (x *CheckReply) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckReply.ProtoReflect.Descriptor instead.
func (*CheckReply) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{8}
}

func (x *CheckReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CheckReply) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_inventory_v1_inventory_proto protoreflect.FileDescriptor

const file_inventory_v1_inventory_proto_rawDesc = "" +
	"\n" +
	"\x1cinventory/v1/inventory.proto\x12\finventory.v1\"u\n" +
	"\tStockItem\x12\x14\n" +
	"\x05skuId\x18\x01 \x01(\x03R\x05skuId\x12\x1c\n" +
	"\tinventory\x18\x02 \x01(\x03R\tinventory\x12\x16\n" +
	"\x06locked\x18\x03 \x01(\x03R\x06locked\x12\x1c\n" +
	"\tavailable\x18\x04 \x01(\x03R\tavailable\"+\n" +
	"\x11StockQueryRequest\x12\x16\n" +
	"\x06skuIds\x18\x01 \x03(\x03R\x06skuIds\"@\n" +
	"\x0fStockQueryReply\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.inventory.v1.StockItemR\x05items\"1\n" +
	"\aSkuItem\x12\x14\n" +
	"\x05skuId\x18\x01 \x01(\x03R\x05skuId\x12\x10\n" +
	"\x03num\x18\x02 \x01(\x05R\x03num\"W\n" +
	"\x0eTryLockRequest\x12\x18\n" +
	"\aorderSn\x18\x01 \x01(\tR\aorderSn\x12+\n" +
	"\x05items\x18\x02 \x03(\v2\x15.inventory.v1.SkuItemR\x05items\"@\n" +
	"\fTryLockReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"]\n" +
	"\x14ConfirmDeductRequest\x12\x18\n" +
	"\aorderSn\x18\x01 \x01(\tR\aorderSn\x12+\n" +
	"\x05items\x18\x02 \x03(\v2\x15.inventory.v1.SkuItemR\x05items\"W\n" +
	"\x0eReleaseRequest\x12\x18\n" +
	"\aorderSn\x18\x01 \x01(\tR\aorderSn\x12+\n" +
	"\x05items\x18\x02 \x03(\v2\x15.inventory.v1.SkuItemR\x05items\">\n" +
	"\n" +
	"CheckReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2\xb0\x02\n" +
	"\tInventory\x12L\n" +
	"\n" +
	"QueryStock\x12\x1f.inventory.v1.StockQueryRequest\x1a\x1d.inventory.v1.StockQueryReply\x12C\n" +
	"\aTryLock\x12\x1c.inventory.v1.TryLockRequest\x1a\x1a.inventory.v1.TryLockReply\x12M\n" +
	"\rConfirmDeduct\x12\".inventory.v1.ConfirmDeductRequest\x1a\x18.inventory.v1.CheckReply\x12A\n" +
	"\aRelease\x12\x1c.inventory.v1.ReleaseRequest\x1a\x18.inventory.v1.CheckReplyB\x1fZ\x1dinventory/api/inventory/v1;v1b\x06proto3"

var (
	file_inventory_v1_inventory_proto_rawDescOnce sync.Once
	file_inventory_v1_inventory_proto_rawDescData []byte
)

func file_inventory_v1_inventory_proto_rawDescGZIP() []byte {
	file_inventory_v1_inventory_proto_rawDescOnce.Do(func() {
		file_inventory_v1_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_v1_inventory_proto_rawDesc), len(file_inventory_v1_inventory_proto_rawDesc)))
	})
	return file_inventory_v1_inventory_proto_rawDescData
}

var file_inventory_v1_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_inventory_v1_inventory_proto_goTypes = []any{
	(*StockItem)(nil),            // 0: inventory.v1.StockItem
	(*StockQueryRequest)(nil),    // 1: inventory.v1.StockQueryRequest
	(*StockQueryReply)(nil),      // 2: inventory.v1.StockQueryReply
	(*SkuItem)(nil),              // 3: inventory.v1.SkuItem
	(*TryLockRequest)(nil),       // 4: inventory.v1.TryLockRequest
	(*TryLockReply)(nil),         // 5: inventory.v1.TryLockReply
	(*ConfirmDeductRequest)(nil), // 6: inventory.v1.ConfirmDeductRequest
	(*ReleaseRequest)(nil),       // 7: inventory.v1.ReleaseRequest
	(*CheckReply)(nil),           // 8: inventory.v1.CheckReply
}
var file_inventory_v1_inventory_proto_depIdxs = []int32{
	0, // 0: inventory.v1.StockQueryReply.items:type_name -> inventory.v1.StockItem
	3, // 1: inventory.v1.TryLockRequest.items:type_name -> inventory.v1.SkuItem
	3, // 2: inventory.v1.ConfirmDeductRequest.items:type_name -> inventory.v1.SkuItem
	3, // 3: inventory.v1.ReleaseRequest.items:type_name -> inventory.v1.SkuItem
	1, // 4: inventory.v1.Inventory.QueryStock:input_type -> inventory.v1.StockQueryRequest
	4, // 5: inventory.v1.Inventory.TryLock:input_type -> inventory.v1.TryLockRequest
	6, // 6: inventory.v1.Inventory.ConfirmDeduct:input_type -> inventory.v1.ConfirmDeductRequest
	7, // 7: inventory.v1.Inventory.Release:input_type -> inventory.v1.ReleaseRequest
	2, // 8: inventory.v1.Inventory.QueryStock:output_type -> inventory.v1.StockQueryReply
	5, // 9: inventory.v1.Inventory.TryLock:output_type -> inventory.v1.TryLockReply
	8, // 10: inventory.v1.Inventory.ConfirmDeduct:output_type -> inventory.v1.CheckReply
	8, // 11: inventory.v1.Inventory.Release:output_type -> inventory.v1.CheckReply
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_inventory_v1_inventory_proto_init() }
func file_inventory_v1_inventory_proto_init() {
	if File_inventory_v1_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_v1_inventory_proto_rawDesc), len(file_inventory_v1_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_v1_inventory_proto_goTypes,
		DependencyIndexes: file_inventory_v1_inventory_proto_depIdxs,
		MessageInfos:      file_inventory_v1_inventory_proto_msgTypes,
	}.Build()
	File_inventory_v1_inventory_proto = out.File
	file_inventory_v1_inventory_proto_goTypes = nil
	file_inventory_v1_inventory_proto_depIdxs = nil
}
