DROP TABLE IF EXISTS order_event_outbox CASCADE;
DROP TABLE IF EXISTS order_pays CASCADE;
DROP TABLE IF EXISTS order_goods CASCADE;
DROP TABLE IF EXISTS order_address CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
