// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/admin/v1/admin.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAddressReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mobile        string                 `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Province      string                 `protobuf:"bytes,4,opt,name=Province,proto3" json:"Province,omitempty"`
	City          string                 `protobuf:"bytes,5,opt,name=City,proto3" json:"City,omitempty"`
	Districts     string                 `protobuf:"bytes,6,opt,name=Districts,proto3" json:"Districts,omitempty"`
	Address       string                 `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	PostCode      string                 `protobuf:"bytes,8,opt,name=post_code,json=postCode,proto3" json:"post_code,omitempty"`
	IsDefault     int32                  `protobuf:"varint,9,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAddressReq) Reset() {
	*x = CreateAddressReq{}
	mi := &file_api_admin_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAddressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAddressReq) ProtoMessage() {}

func (x *CreateAddressReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAddressReq.ProtoReflect.Descriptor instead.
func (*CreateAddressReq) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAddressReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CreateAddressReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAddressReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *CreateAddressReq) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *CreateAddressReq) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateAddressReq) GetDistricts() string {
	if x != nil {
		return x.Districts
	}
	return ""
}

func (x *CreateAddressReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateAddressReq) GetPostCode() string {
	if x != nil {
		return x.PostCode
	}
	return ""
}

func (x *CreateAddressReq) GetIsDefault() int32 {
	if x != nil {
		return x.IsDefault
	}
	return 0
}

type UpdateAddressReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mobile        string                 `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Province      string                 `protobuf:"bytes,4,opt,name=Province,proto3" json:"Province,omitempty"`
	City          string                 `protobuf:"bytes,5,opt,name=City,proto3" json:"City,omitempty"`
	Districts     string                 `protobuf:"bytes,6,opt,name=Districts,proto3" json:"Districts,omitempty"`
	Address       string                 `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	PostCode      string                 `protobuf:"bytes,8,opt,name=post_code,json=postCode,proto3" json:"post_code,omitempty"`
	IsDefault     int32                  `protobuf:"varint,9,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	Id            int64                  `protobuf:"varint,10,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAddressReq) Reset() {
	*x = UpdateAddressReq{}
	mi := &file_api_admin_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAddressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAddressReq) ProtoMessage() {}

func (x *UpdateAddressReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAddressReq.ProtoReflect.Descriptor instead.
func (*UpdateAddressReq) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateAddressReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UpdateAddressReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateAddressReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *UpdateAddressReq) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *UpdateAddressReq) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UpdateAddressReq) GetDistricts() string {
	if x != nil {
		return x.Districts
	}
	return ""
}

func (x *UpdateAddressReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UpdateAddressReq) GetPostCode() string {
	if x != nil {
		return x.PostCode
	}
	return ""
}

func (x *UpdateAddressReq) GetIsDefault() int32 {
	if x != nil {
		return x.IsDefault
	}
	return 0
}

func (x *UpdateAddressReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AddressInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mobile        string                 `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Province      string                 `protobuf:"bytes,4,opt,name=Province,proto3" json:"Province,omitempty"`
	City          string                 `protobuf:"bytes,5,opt,name=City,proto3" json:"City,omitempty"`
	Districts     string                 `protobuf:"bytes,6,opt,name=Districts,proto3" json:"Districts,omitempty"`
	Address       string                 `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	PostCode      string                 `protobuf:"bytes,8,opt,name=post_code,json=postCode,proto3" json:"post_code,omitempty"`
	IsDefault     int32                  `protobuf:"varint,9,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressInfo) Reset() {
	*x = AddressInfo{}
	mi := &file_api_admin_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressInfo) ProtoMessage() {}

func (x *AddressInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressInfo.ProtoReflect.Descriptor instead.
func (*AddressInfo) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *AddressInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddressInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddressInfo) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *AddressInfo) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *AddressInfo) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *AddressInfo) GetDistricts() string {
	if x != nil {
		return x.Districts
	}
	return ""
}

func (x *AddressInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AddressInfo) GetPostCode() string {
	if x != nil {
		return x.PostCode
	}
	return ""
}

func (x *AddressInfo) GetIsDefault() int32 {
	if x != nil {
		return x.IsDefault
	}
	return 0
}

type ListAddressReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAddressReq) Reset() {
	*x = ListAddressReq{}
	mi := &file_api_admin_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAddressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAddressReq) ProtoMessage() {}

func (x *ListAddressReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAddressReq.ProtoReflect.Descriptor instead.
func (*ListAddressReq) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *ListAddressReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type ListAddressReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*AddressInfo         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAddressReply) Reset() {
	*x = ListAddressReply{}
	mi := &file_api_admin_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAddressReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAddressReply) ProtoMessage() {}

func (x *ListAddressReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAddressReply.ProtoReflect.Descriptor instead.
func (*ListAddressReply) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *ListAddressReply) GetResults() []*AddressInfo {
	if x != nil {
		return x.Results
	}
	return nil
}

type AddressReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid           int64                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressReq) Reset() {
	*x = AddressReq{}
	mi := &file_api_admin_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressReq) ProtoMessage() {}

func (x *AddressReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressReq.ProtoReflect.Descriptor instead.
func (*AddressReq) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *AddressReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddressReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type CheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_api_admin_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *CheckResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Data returned by registration and login
type RegisterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Mobile        string                 `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Token         string                 `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	ExpiredAt     int64                  `protobuf:"varint,6,opt,name=expiredAt,proto3" json:"expiredAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReply) Reset() {
	*x = RegisterReply{}
	mi := &file_api_admin_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReply) ProtoMessage() {}

func (x *RegisterReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReply.ProtoReflect.Descriptor instead.
func (*RegisterReply) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RegisterReply) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *RegisterReply) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterReply) GetExpiredAt() int64 {
	if x != nil {
		return x.ExpiredAt
	}
	return 0
}

type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_api_admin_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_admin_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *RegisterReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_api_admin_v1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_admin_proto_rawDescGZIP(), []int{9}
}

func (x *LoginReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// user Detail returned
type UserDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Mobile        string                 `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	NickName      string                 `protobuf:"bytes,3,opt,name=nickName,proto3" json:"nickName,omitempty"`
	Birthday      int64                  `protobuf:"varint,4,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Gender        string                 `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Role          int32                  `protobuf:"varint,6,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDetailResponse) Reset() {
	*x = UserDetailResponse{}
	mi := &file_api_admin_v1_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetailResponse) ProtoMessage() {}

func (x *UserDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetailResponse.ProtoReflect.Descriptor instead.
func (*UserDetailResponse) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_admin_proto_rawDescGZIP(), []int{10}
}

func (x *UserDetailResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserDetailResponse) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *UserDetailResponse) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *UserDetailResponse) GetBirthday() int64 {
	if x != nil {
		return x.Birthday
	}
	return 0
}

func (x *UserDetailResponse) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *UserDetailResponse) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

type CaptchaReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaptchaId     string                 `protobuf:"bytes,1,opt,name=captchaId,proto3" json:"captchaId,omitempty"`
	PicPath       string                 `protobuf:"bytes,2,opt,name=picPath,proto3" json:"picPath,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptchaReply) Reset() {
	*x = CaptchaReply{}
	mi := &file_api_admin_v1_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptchaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptchaReply) ProtoMessage() {}

func (x *CaptchaReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptchaReply.ProtoReflect.Descriptor instead.
func (*CaptchaReply) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_admin_proto_rawDescGZIP(), []int{11}
}

func (x *CaptchaReply) GetCaptchaId() string {
	if x != nil {
		return x.CaptchaId
	}
	return ""
}

func (x *CaptchaReply) GetPicPath() string {
	if x != nil {
		return x.PicPath
	}
	return ""
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_api_admin_v1_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_admin_proto_rawDescGZIP(), []int{12}
}

func (x *RefreshTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GoodsListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Keywords      string                 `protobuf:"bytes,3,opt,name=keywords,proto3" json:"keywords,omitempty"`
	CategoryId    int64                  `protobuf:"varint,4,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	BrandId       int64                  `protobuf:"varint,5,opt,name=brandId,proto3" json:"brandId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsListRequest) Reset() {
	*x = GoodsListRequest{}
	mi := &file_api_admin_v1_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsListRequest) ProtoMessage() {}

func (x *GoodsListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsListRequest.ProtoReflect.Descriptor instead.
func (*GoodsListRequest) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_admin_proto_rawDescGZIP(), []int{13}
}

func (x *GoodsListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GoodsListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GoodsListRequest) GetKeywords() string {
	if x != nil {
		return x.Keywords
	}
	return ""
}

func (x *GoodsListRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *GoodsListRequest) GetBrandId() int64 {
	if x != nil {
		return x.BrandId
	}
	return 0
}

type GoodsItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	GoodsSn       string                 `protobuf:"bytes,3,opt,name=goodsSn,proto3" json:"goodsSn,omitempty"`
	MarketPrice   int64                  `protobuf:"varint,4,opt,name=marketPrice,proto3" json:"marketPrice,omitempty"`
	OnSale        bool                   `protobuf:"varint,5,opt,name=onSale,proto3" json:"onSale,omitempty"`
	IsNew         bool                   `protobuf:"varint,6,opt,name=isNew,proto3" json:"isNew,omitempty"`
	IsHot         bool                   `protobuf:"varint,7,opt,name=isHot,proto3" json:"isHot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsItem) Reset() {
	*x = GoodsItem{}
	mi := &file_api_admin_v1_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsItem) ProtoMessage() {}

func (x *GoodsItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsItem.ProtoReflect.Descriptor instead.
func (*GoodsItem) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_admin_proto_rawDescGZIP(), []int{14}
}

func (x *GoodsItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GoodsItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GoodsItem) GetGoodsSn() string {
	if x != nil {
		return x.GoodsSn
	}
	return ""
}

func (x *GoodsItem) GetMarketPrice() int64 {
	if x != nil {
		return x.MarketPrice
	}
	return 0
}

func (x *GoodsItem) GetOnSale() bool {
	if x != nil {
		return x.OnSale
	}
	return false
}

func (x *GoodsItem) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

func (x *GoodsItem) GetIsHot() bool {
	if x != nil {
		return x.IsHot
	}
	return false
}

type GoodsListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*GoodsItem           `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsListReply) Reset() {
	*x = GoodsListReply{}
	mi := &file_api_admin_v1_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsListReply) ProtoMessage() {}

func (x *GoodsListReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsListReply.ProtoReflect.Descriptor instead.
func (*GoodsListReply) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_admin_proto_rawDescGZIP(), []int{15}
}

func (x *GoodsListReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GoodsListReply) GetList() []*GoodsItem {
	if x != nil {
		return x.List
	}
	return nil
}

type UpdateGoodsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NameAlias       string                 `protobuf:"bytes,3,opt,name=nameAlias,proto3" json:"nameAlias,omitempty"`
	GoodsBrief      string                 `protobuf:"bytes,4,opt,name=goodsBrief,proto3" json:"goodsBrief,omitempty"`
	GoodsFrontImage string                 `protobuf:"bytes,5,opt,name=goodsFrontImage,proto3" json:"goodsFrontImage,omitempty"`
	MarketPrice     int64                  `protobuf:"varint,6,opt,name=marketPrice,proto3" json:"marketPrice,omitempty"`
	ShipFree        bool                   `protobuf:"varint,7,opt,name=shipFree,proto3" json:"shipFree,omitempty"`
	IsNew           bool                   `protobuf:"varint,8,opt,name=isNew,proto3" json:"isNew,omitempty"`
	IsHot           bool                   `protobuf:"varint,9,opt,name=isHot,proto3" json:"isHot,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateGoodsRequest) Reset() {
	*x = UpdateGoodsRequest{}
	mi := &file_api_admin_v1_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGoodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGoodsRequest) ProtoMessage() {}

func (x *UpdateGoodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGoodsRequest.ProtoReflect.Descriptor instead.
func (*UpdateGoodsRequest) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_admin_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateGoodsRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateGoodsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateGoodsRequest) GetNameAlias() string {
	if x != nil {
		return x.NameAlias
	}
	return ""
}

func (x *UpdateGoodsRequest) GetGoodsBrief() string {
	if x != nil {
		return x.GoodsBrief
	}
	return ""
}

func (x *UpdateGoodsRequest) GetGoodsFrontImage() string {
	if x != nil {
		return x.GoodsFrontImage
	}
	return ""
}

func (x *UpdateGoodsRequest) GetMarketPrice() int64 {
	if x != nil {
		return x.MarketPrice
	}
	return 0
}

func (x *UpdateGoodsRequest) GetShipFree() bool {
	if x != nil {
		return x.ShipFree
	}
	return false
}

func (x *UpdateGoodsRequest) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

func (x *UpdateGoodsRequest) GetIsHot() bool {
	if x != nil {
		return x.IsHot
	}
	return false
}

type DeleteGoodsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGoodsRequest) Reset() {
	*x = DeleteGoodsRequest{}
	mi := &file_api_admin_v1_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGoodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGoodsRequest) ProtoMessage() {}

func (x *DeleteGoodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGoodsRequest.ProtoReflect.Descriptor instead.
func (*DeleteGoodsRequest) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_admin_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteGoodsRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateGoodsStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OnSale        bool                   `protobuf:"varint,2,opt,name=onSale,proto3" json:"onSale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGoodsStatusRequest) Reset() {
	*x = UpdateGoodsStatusRequest{}
	mi := &file_api_admin_v1_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGoodsStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGoodsStatusRequest) ProtoMessage() {}

func (x *UpdateGoodsStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGoodsStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateGoodsStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_admin_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateGoodsStatusRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateGoodsStatusRequest) GetOnSale() bool {
	if x != nil {
		return x.OnSale
	}
	return false
}

var File_api_admin_v1_admin_proto protoreflect.FileDescriptor

const file_api_admin_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x18api/admin/v1/admin.proto\x12\x0eadmin.admin.v1\x1a\x17validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xab\x02\n" +
	"\x10CreateAddressReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x12 \n" +
	"\x06mobile\x18\x03 \x01(\tB\b\xfaB\x05r\x03\x98\x01\vR\x06mobile\x12#\n" +
	"\bProvince\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\bProvince\x12\x1b\n" +
	"\x04City\x18\x05 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04City\x12%\n" +
	"\tDistricts\x18\x06 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\tDistricts\x12!\n" +
	"\aaddress\x18\a \x01(\tB\a\xfaB\x04r\x02\x10\x01R\aaddress\x12\x1b\n" +
	"\tpost_code\x18\b \x01(\tR\bpostCode\x12\x1d\n" +
	"\n" +
	"is_default\x18\t \x01(\x05R\tisDefault\"\xbb\x02\n" +
	"\x10UpdateAddressReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\x06mobile\x18\x03 \x01(\tB\b\xfaB\x05r\x03\x98\x01\vR\x06mobile\x12#\n" +
	"\bProvince\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\bProvince\x12\x1b\n" +
	"\x04City\x18\x05 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04City\x12%\n" +
	"\tDistricts\x18\x06 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\tDistricts\x12!\n" +
	"\aaddress\x18\a \x01(\tB\a\xfaB\x04r\x02\x10\x01R\aaddress\x12\x1b\n" +
	"\tpost_code\x18\b \x01(\tR\bpostCode\x12\x1d\n" +
	"\n" +
	"is_default\x18\t \x01(\x05R\tisDefault\x12\x17\n" +
	"\x02id\x18\n" +
	" \x01(\x03B\a\xfaB\x04\"\x02(\x01R\x02id\"\x80\x02\n" +
	"\vAddressInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x12 \n" +
	"\x06mobile\x18\x03 \x01(\tB\b\xfaB\x05r\x03\x98\x01\vR\x06mobile\x12\x1a\n" +
	"\bProvince\x18\x04 \x01(\tR\bProvince\x12\x12\n" +
	"\x04City\x18\x05 \x01(\tR\x04City\x12\x1c\n" +
	"\tDistricts\x18\x06 \x01(\tR\tDistricts\x12\x18\n" +
	"\aaddress\x18\a \x01(\tR\aaddress\x12\x1b\n" +
	"\tpost_code\x18\b \x01(\tR\bpostCode\x12\x1d\n" +
	"\n" +
	"is_default\x18\t \x01(\x05R\tisDefault\"\"\n" +
	"\x0eListAddressReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\"I\n" +
	"\x10ListAddressReply\x125\n" +
	"\aresults\x18\x01 \x03(\v2\x1b.admin.admin.v1.AddressInfoR\aresults\"7\n" +
	"\n" +
	"AddressReq\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02(\x01R\x02id\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x03R\x03uid\")\n" +
	"\rCheckResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x87\x01\n" +
	"\rRegisterReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06mobile\x18\x03 \x01(\tR\x06mobile\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x14\n" +
	"\x05token\x18\x05 \x01(\tR\x05token\x12\x1c\n" +
	"\texpiredAt\x18\x06 \x01(\x03R\texpiredAt\"{\n" +
	"\vRegisterReq\x12 \n" +
	"\x06mobile\x18\x01 \x01(\tB\b\xfaB\x05r\x03\x98\x01\vR\x06mobile\x12%\n" +
	"\busername\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x03\x18\x0fR\busername\x12#\n" +
	"\bpassword\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\bR\bpassword\"T\n" +
	"\bLoginReq\x12#\n" +
	"\busername\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x03R\busername\x12#\n" +
	"\bpassword\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\bR\bpassword\"\xa0\x01\n" +
	"\x12UserDetailResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06mobile\x18\x02 \x01(\tR\x06mobile\x12\x1a\n" +
	"\bnickName\x18\x03 \x01(\tR\bnickName\x12\x1a\n" +
	"\bbirthday\x18\x04 \x01(\x03R\bbirthday\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\tR\x06gender\x12\x12\n" +
	"\x04role\x18\x06 \x01(\x05R\x04role\"F\n" +
	"\fCaptchaReply\x12\x1c\n" +
	"\tcaptchaId\x18\x01 \x01(\tR\tcaptchaId\x12\x18\n" +
	"\apicPath\x18\x02 \x01(\tR\apicPath\"+\n" +
	"\x13RefreshTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x98\x01\n" +
	"\x10GoodsListRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\x12\x1a\n" +
	"\bkeywords\x18\x03 \x01(\tR\bkeywords\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x04 \x01(\x03R\n" +
	"categoryId\x12\x18\n" +
	"\abrandId\x18\x05 \x01(\x03R\abrandId\"\xaf\x01\n" +
	"\tGoodsItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\agoodsSn\x18\x03 \x01(\tR\agoodsSn\x12 \n" +
	"\vmarketPrice\x18\x04 \x01(\x03R\vmarketPrice\x12\x16\n" +
	"\x06onSale\x18\x05 \x01(\bR\x06onSale\x12\x14\n" +
	"\x05isNew\x18\x06 \x01(\bR\x05isNew\x12\x14\n" +
	"\x05isHot\x18\a \x01(\bR\x05isHot\"U\n" +
	"\x0eGoodsListReply\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12-\n" +
	"\x04list\x18\x02 \x03(\v2\x19.admin.admin.v1.GoodsItemR\x04list\"\x93\x02\n" +
	"\x12UpdateGoodsRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02(\x01R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tnameAlias\x18\x03 \x01(\tR\tnameAlias\x12\x1e\n" +
	"\n" +
	"goodsBrief\x18\x04 \x01(\tR\n" +
	"goodsBrief\x12(\n" +
	"\x0fgoodsFrontImage\x18\x05 \x01(\tR\x0fgoodsFrontImage\x12 \n" +
	"\vmarketPrice\x18\x06 \x01(\x03R\vmarketPrice\x12\x1a\n" +
	"\bshipFree\x18\a \x01(\bR\bshipFree\x12\x14\n" +
	"\x05isNew\x18\b \x01(\bR\x05isNew\x12\x14\n" +
	"\x05isHot\x18\t \x01(\bR\x05isHot\"-\n" +
	"\x12DeleteGoodsRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02(\x01R\x02id\"K\n" +
	"\x18UpdateGoodsStatusRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02(\x01R\x02id\x12\x16\n" +
	"\x06onSale\x18\x02 \x01(\bR\x06onSale2\xe6\v\n" +
	"\x05admin\x12f\n" +
	"\bRegister\x12\x1b.admin.admin.v1.RegisterReq\x1a\x1d.admin.admin.v1.RegisterReply\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/users/register\x12q\n" +
	"\fRefreshToken\x12#.admin.admin.v1.RefreshTokenRequest\x1a\x1d.admin.admin.v1.RegisterReply\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/users/refresh\x12]\n" +
	"\x05Login\x12\x18.admin.admin.v1.LoginReq\x1a\x1d.admin.admin.v1.RegisterReply\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/users/login\x12[\n" +
	"\aCaptcha\x12\x16.google.protobuf.Empty\x1a\x1c.admin.admin.v1.CaptchaReply\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/users/captcha\x12_\n" +
	"\x06Detail\x12\x16.google.protobuf.Empty\x1a\".admin.admin.v1.UserDetailResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/users/detail\x12n\n" +
	"\rCreateAddress\x12 .admin.admin.v1.CreateAddressReq\x1a\x1b.admin.admin.v1.AddressInfo\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/address/create\x12k\n" +
	"\x10AddressListByUid\x12\x16.google.protobuf.Empty\x1a .admin.admin.v1.ListAddressReply\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/address/list/uid\x12p\n" +
	"\rUpdateAddress\x12 .admin.admin.v1.UpdateAddressReq\x1a\x1d.admin.admin.v1.CheckResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\x1a\x13/api/address/update\x12l\n" +
	"\x0eDefaultAddress\x12\x1a.admin.admin.v1.AddressReq\x1a\x1d.admin.admin.v1.CheckResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\x1a\x14/api/address/default\x12g\n" +
	"\rDeleteAddress\x12\x1a.admin.admin.v1.AddressReq\x1a\x1d.admin.admin.v1.CheckResponse\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13/api/address/delete\x12f\n" +
	"\tGoodsList\x12 .admin.admin.v1.GoodsListRequest\x1a\x1e.admin.admin.v1.GoodsListReply\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/goods/list\x12n\n" +
	"\vUpdateGoods\x12\".admin.admin.v1.UpdateGoodsRequest\x1a\x1d.admin.admin.v1.CheckResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\x1a\x11/api/goods/update\x12k\n" +
	"\vDeleteGoods\x12\".admin.admin.v1.DeleteGoodsRequest\x1a\x1d.admin.admin.v1.CheckResponse\"\x19\x82\xd3\xe4\x93\x02\x13*\x11/api/goods/delete\x12z\n" +
	"\x11UpdateGoodsStatus\x12(.admin.admin.v1.UpdateGoodsStatusRequest\x1a\x1d.admin.admin.v1.CheckResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\x1a\x11/api/goods/statusB\x17Z\x15admin/api/admin/v1;v1b\x06proto3"

var (
	file_api_admin_v1_admin_proto_rawDescOnce sync.Once
	file_api_admin_v1_admin_proto_rawDescData []byte
)

func file_api_admin_v1_admin_proto_rawDescGZIP() []byte {
	file_api_admin_v1_admin_proto_rawDescOnce.Do(func() {
		file_api_admin_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_admin_v1_admin_proto_rawDesc), len(file_api_admin_v1_admin_proto_rawDesc)))
	})
	return file_api_admin_v1_admin_proto_rawDescData
}

var file_api_admin_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_api_admin_v1_admin_proto_goTypes = []any{
	(*CreateAddressReq)(nil),         // 0: admin.admin.v1.CreateAddressReq
	(*UpdateAddressReq)(nil),         // 1: admin.admin.v1.UpdateAddressReq
	(*AddressInfo)(nil),              // 2: admin.admin.v1.AddressInfo
	(*ListAddressReq)(nil),           // 3: admin.admin.v1.ListAddressReq
	(*ListAddressReply)(nil),         // 4: admin.admin.v1.ListAddressReply
	(*AddressReq)(nil),               // 5: admin.admin.v1.AddressReq
	(*CheckResponse)(nil),            // 6: admin.admin.v1.CheckResponse
	(*RegisterReply)(nil),            // 7: admin.admin.v1.RegisterReply
	(*RegisterReq)(nil),              // 8: admin.admin.v1.RegisterReq
	(*LoginReq)(nil),                 // 9: admin.admin.v1.LoginReq
	(*UserDetailResponse)(nil),       // 10: admin.admin.v1.UserDetailResponse
	(*CaptchaReply)(nil),             // 11: admin.admin.v1.CaptchaReply
	(*RefreshTokenRequest)(nil),      // 12: admin.admin.v1.RefreshTokenRequest
	(*GoodsListRequest)(nil),         // 13: admin.admin.v1.GoodsListRequest
	(*GoodsItem)(nil),                // 14: admin.admin.v1.GoodsItem
	(*GoodsListReply)(nil),           // 15: admin.admin.v1.GoodsListReply
	(*UpdateGoodsRequest)(nil),       // 16: admin.admin.v1.UpdateGoodsRequest
	(*DeleteGoodsRequest)(nil),       // 17: admin.admin.v1.DeleteGoodsRequest
	(*UpdateGoodsStatusRequest)(nil), // 18: admin.admin.v1.UpdateGoodsStatusRequest
	(*emptypb.Empty)(nil),            // 19: google.protobuf.Empty
}
var file_api_admin_v1_admin_proto_depIdxs = []int32{
	2,  // 0: admin.admin.v1.ListAddressReply.results:type_name -> admin.admin.v1.AddressInfo
	14, // 1: admin.admin.v1.GoodsListReply.list:type_name -> admin.admin.v1.GoodsItem
	8,  // 2: admin.admin.v1.admin.Register:input_type -> admin.admin.v1.RegisterReq
	12, // 3: admin.admin.v1.admin.RefreshToken:input_type -> admin.admin.v1.RefreshTokenRequest
	9,  // 4: admin.admin.v1.admin.Login:input_type -> admin.admin.v1.LoginReq
	19, // 5: admin.admin.v1.admin.Captcha:input_type -> google.protobuf.Empty
	19, // 6: admin.admin.v1.admin.Detail:input_type -> google.protobuf.Empty
	0,  // 7: admin.admin.v1.admin.CreateAddress:input_type -> admin.admin.v1.CreateAddressReq
	19, // 8: admin.admin.v1.admin.AddressListByUid:input_type -> google.protobuf.Empty
	1,  // 9: admin.admin.v1.admin.UpdateAddress:input_type -> admin.admin.v1.UpdateAddressReq
	5,  // 10: admin.admin.v1.admin.DefaultAddress:input_type -> admin.admin.v1.AddressReq
	5,  // 11: admin.admin.v1.admin.DeleteAddress:input_type -> admin.admin.v1.AddressReq
	13, // 12: admin.admin.v1.admin.GoodsList:input_type -> admin.admin.v1.GoodsListRequest
	16, // 13: admin.admin.v1.admin.UpdateGoods:input_type -> admin.admin.v1.UpdateGoodsRequest
	17, // 14: admin.admin.v1.admin.DeleteGoods:input_type -> admin.admin.v1.DeleteGoodsRequest
	18, // 15: admin.admin.v1.admin.UpdateGoodsStatus:input_type -> admin.admin.v1.UpdateGoodsStatusRequest
	7,  // 16: admin.admin.v1.admin.Register:output_type -> admin.admin.v1.RegisterReply
	7,  // 17: admin.admin.v1.admin.RefreshToken:output_type -> admin.admin.v1.RegisterReply
	7,  // 18: admin.admin.v1.admin.Login:output_type -> admin.admin.v1.RegisterReply
	11, // 19: admin.admin.v1.admin.Captcha:output_type -> admin.admin.v1.CaptchaReply
	10, // 20: admin.admin.v1.admin.Detail:output_type -> admin.admin.v1.UserDetailResponse
	2,  // 21: admin.admin.v1.admin.CreateAddress:output_type -> admin.admin.v1.AddressInfo
	4,  // 22: admin.admin.v1.admin.AddressListByUid:output_type -> admin.admin.v1.ListAddressReply
	6,  // 23: admin.admin.v1.admin.UpdateAddress:output_type -> admin.admin.v1.CheckResponse
	6,  // 24: admin.admin.v1.admin.DefaultAddress:output_type -> admin.admin.v1.CheckResponse
	6,  // 25: admin.admin.v1.admin.DeleteAddress:output_type -> admin.admin.v1.CheckResponse
	15, // 26: admin.admin.v1.admin.GoodsList:output_type -> admin.admin.v1.GoodsListReply
	6,  // 27: admin.admin.v1.admin.UpdateGoods:output_type -> admin.admin.v1.CheckResponse
	6,  // 28: admin.admin.v1.admin.DeleteGoods:output_type -> admin.admin.v1.CheckResponse
	6,  // 29: admin.admin.v1.admin.UpdateGoodsStatus:output_type -> admin.admin.v1.CheckResponse
	16, // [16:30] is the sub-list for method output_type
	2,  // [2:16] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_admin_v1_admin_proto_init() }
func file_api_admin_v1_admin_proto_init() {
	if File_api_admin_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_admin_v1_admin_proto_rawDesc), len(file_api_admin_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_admin_v1_admin_proto_goTypes,
		DependencyIndexes: file_api_admin_v1_admin_proto_depIdxs,
		MessageInfos:      file_api_admin_v1_admin_proto_msgTypes,
	}.Build()
	File_api_admin_v1_admin_proto = out.File
	file_api_admin_v1_admin_proto_goTypes = nil
	file_api_admin_v1_admin_proto_depIdxs = nil
}
