// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/service/order/v1/order.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CartItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CartId        int64                  `protobuf:"varint,1,opt,name=cartId,proto3" json:"cartId,omitempty"`
	SkuId         int64                  `protobuf:"varint,2,opt,name=skuId,proto3" json:"skuId,omitempty"`
	SkuPrice      int64                  `protobuf:"varint,3,opt,name=skuPrice,proto3" json:"skuPrice,omitempty"`
	SkuNum        int32                  `protobuf:"varint,4,opt,name=skuNum,proto3" json:"skuNum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItem) Reset() {
	*x = CartItem{}
	mi := &file_api_service_order_v1_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItem) ProtoMessage() {}

func (x *CartItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_order_v1_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItem.ProtoReflect.Descriptor instead.
func (*CartItem) Descriptor() ([]byte, []int) {
	return file_api_service_order_v1_order_proto_rawDescGZIP(), []int{0}
}

func (x *CartItem) GetCartId() int64 {
	if x != nil {
		return x.CartId
	}
	return 0
}

func (x *CartItem) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *CartItem) GetSkuPrice() int64 {
	if x != nil {
		return x.SkuPrice
	}
	return 0
}

func (x *CartItem) GetSkuNum() int32 {
	if x != nil {
		return x.SkuNum
	}
	return 0
}

type OrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Address       int64                  `protobuf:"varint,3,opt,name=address,proto3" json:"address,omitempty"`
	CartItem      []*CartItem            `protobuf:"bytes,4,rep,name=cartItem,proto3" json:"cartItem,omitempty"` //  购物车购买
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderRequest) Reset() {
	*x = OrderRequest{}
	mi := &file_api_service_order_v1_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRequest) ProtoMessage() {}

func (x *OrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_order_v1_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRequest.ProtoReflect.Descriptor instead.
func (*OrderRequest) Descriptor() ([]byte, []int) {
	return file_api_service_order_v1_order_proto_rawDescGZIP(), []int{1}
}

func (x *OrderRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderRequest) GetAddress() int64 {
	if x != nil {
		return x.Address
	}
	return 0
}

func (x *OrderRequest) GetCartItem() []*CartItem {
	if x != nil {
		return x.CartItem
	}
	return nil
}

type OrderInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	OrderSn       string                 `protobuf:"bytes,3,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	PayType       string                 `protobuf:"bytes,4,opt,name=payType,proto3" json:"payType,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Post          string                 `protobuf:"bytes,6,opt,name=post,proto3" json:"post,omitempty"`
	Total         int64                  `protobuf:"varint,7,opt,name=total,proto3" json:"total,omitempty"`
	Address       string                 `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	Name          string                 `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`
	Mobile        string                 `protobuf:"bytes,10,opt,name=mobile,proto3" json:"mobile,omitempty"`
	AddTime       string                 `protobuf:"bytes,11,opt,name=addTime,proto3" json:"addTime,omitempty"`
	Goods         []*OrderGoodsInfo      `protobuf:"bytes,12,rep,name=goods,proto3" json:"goods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderInfoResponse) Reset() {
	*x = OrderInfoResponse{}
	mi := &file_api_service_order_v1_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfoResponse) ProtoMessage() {}

func (x *OrderInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_order_v1_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfoResponse.ProtoReflect.Descriptor instead.
func (*OrderInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_service_order_v1_order_proto_rawDescGZIP(), []int{2}
}

func (x *OrderInfoResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderInfoResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderInfoResponse) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *OrderInfoResponse) GetPayType() string {
	if x != nil {
		return x.PayType
	}
	return ""
}

func (x *OrderInfoResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderInfoResponse) GetPost() string {
	if x != nil {
		return x.Post
	}
	return ""
}

func (x *OrderInfoResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *OrderInfoResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *OrderInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderInfoResponse) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *OrderInfoResponse) GetAddTime() string {
	if x != nil {
		return x.AddTime
	}
	return ""
}

func (x *OrderInfoResponse) GetGoods() []*OrderGoodsInfo {
	if x != nil {
		return x.Goods
	}
	return nil
}

type OrderGoodsInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SkuId         int64                  `protobuf:"varint,2,opt,name=skuId,proto3" json:"skuId,omitempty"`
	SkuName       string                 `protobuf:"bytes,3,opt,name=skuName,proto3" json:"skuName,omitempty"`
	SkuPrice      int64                  `protobuf:"varint,4,opt,name=skuPrice,proto3" json:"skuPrice,omitempty"`
	Num           int32                  `protobuf:"varint,5,opt,name=num,proto3" json:"num,omitempty"`
	TotalPrice    int64                  `protobuf:"varint,6,opt,name=totalPrice,proto3" json:"totalPrice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderGoodsInfo) Reset() {
	*x = OrderGoodsInfo{}
	mi := &file_api_service_order_v1_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderGoodsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderGoodsInfo) ProtoMessage() {}

func (x *OrderGoodsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_order_v1_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderGoodsInfo.ProtoReflect.Descriptor instead.
func (*OrderGoodsInfo) Descriptor() ([]byte, []int) {
	return file_api_service_order_v1_order_proto_rawDescGZIP(), []int{3}
}

func (x *OrderGoodsInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderGoodsInfo) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *OrderGoodsInfo) GetSkuName() string {
	if x != nil {
		return x.SkuName
	}
	return ""
}

func (x *OrderGoodsInfo) GetSkuPrice() int64 {
	if x != nil {
		return x.SkuPrice
	}
	return 0
}

func (x *OrderGoodsInfo) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *OrderGoodsInfo) GetTotalPrice() int64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	OrderSn       string                 `protobuf:"bytes,2,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_api_service_order_v1_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_order_v1_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_service_order_v1_order_proto_rawDescGZIP(), []int{4}
}

func (x *CancelOrderRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CancelOrderRequest) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

type CheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_api_service_order_v1_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_order_v1_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_api_service_order_v1_order_proto_rawDescGZIP(), []int{5}
}

func (x *CheckResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	OrderSn       string                 `protobuf:"bytes,2,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_api_service_order_v1_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_order_v1_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_service_order_v1_order_proto_rawDescGZIP(), []int{6}
}

func (x *GetOrderRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetOrderRequest) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

type ListOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderRequest) Reset() {
	*x = ListOrderRequest{}
	mi := &file_api_service_order_v1_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderRequest) ProtoMessage() {}

func (x *ListOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_order_v1_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderRequest.ProtoReflect.Descriptor instead.
func (*ListOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_service_order_v1_order_proto_rawDescGZIP(), []int{7}
}

func (x *ListOrderRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListOrderRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOrderRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*OrderInfoResponse   `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderReply) Reset() {
	*x = ListOrderReply{}
	mi := &file_api_service_order_v1_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderReply) ProtoMessage() {}

func (x *ListOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_order_v1_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderReply.ProtoReflect.Descriptor instead.
func (*ListOrderReply) Descriptor() ([]byte, []int) {
	return file_api_service_order_v1_order_proto_rawDescGZIP(), []int{8}
}

func (x *ListOrderReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListOrderReply) GetList() []*OrderInfoResponse {
	if x != nil {
		return x.List
	}
	return nil
}

var File_api_service_order_v1_order_proto protoreflect.FileDescriptor

const file_api_service_order_v1_order_proto_rawDesc = "" +
	"\n" +
	" api/service/order/v1/order.proto\x12\border.v1\x1a\x17validate/validate.proto\"l\n" +
	"\bCartItem\x12\x16\n" +
	"\x06cartId\x18\x01 \x01(\x03R\x06cartId\x12\x14\n" +
	"\x05skuId\x18\x02 \x01(\x03R\x05skuId\x12\x1a\n" +
	"\bskuPrice\x18\x03 \x01(\x03R\bskuPrice\x12\x16\n" +
	"\x06skuNum\x18\x04 \x01(\x05R\x06skuNum\"\x92\x01\n" +
	"\fOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\x06userId\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06userId\x12!\n" +
	"\aaddress\x18\x03 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\aaddress\x12.\n" +
	"\bcartItem\x18\x04 \x03(\v2\x12.order.v1.CartItemR\bcartItem\"\xc1\x02\n" +
	"\x11OrderInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x18\n" +
	"\aorderSn\x18\x03 \x01(\tR\aorderSn\x12\x18\n" +
	"\apayType\x18\x04 \x01(\tR\apayType\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x12\n" +
	"\x04post\x18\x06 \x01(\tR\x04post\x12\x14\n" +
	"\x05total\x18\a \x01(\x03R\x05total\x12\x18\n" +
	"\aaddress\x18\b \x01(\tR\aaddress\x12\x12\n" +
	"\x04name\x18\t \x01(\tR\x04name\x12\x16\n" +
	"\x06mobile\x18\n" +
	" \x01(\tR\x06mobile\x12\x18\n" +
	"\aaddTime\x18\v \x01(\tR\aaddTime\x12.\n" +
	"\x05goods\x18\f \x03(\v2\x18.order.v1.OrderGoodsInfoR\x05goods\"\x9e\x01\n" +
	"\x0eOrderGoodsInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05skuId\x18\x02 \x01(\x03R\x05skuId\x12\x18\n" +
	"\askuName\x18\x03 \x01(\tR\askuName\x12\x1a\n" +
	"\bskuPrice\x18\x04 \x01(\x03R\bskuPrice\x12\x10\n" +
	"\x03num\x18\x05 \x01(\x05R\x03num\x12\x1e\n" +
	"\n" +
	"totalPrice\x18\x06 \x01(\x03R\n" +
	"totalPrice\"F\n" +
	"\x12CancelOrderRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x18\n" +
	"\aorderSn\x18\x02 \x01(\tR\aorderSn\")\n" +
	"\rCheckResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"C\n" +
	"\x0fGetOrderRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x18\n" +
	"\aorderSn\x18\x02 \x01(\tR\aorderSn\"Z\n" +
	"\x10ListOrderRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x05R\bpageSize\"W\n" +
	"\x0eListOrderReply\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12/\n" +
	"\x04list\x18\x02 \x03(\v2\x1b.order.v1.OrderInfoResponseR\x04list2\x99\x02\n" +
	"\x05Order\x12B\n" +
	"\vCreateOrder\x12\x16.order.v1.OrderRequest\x1a\x1b.order.v1.OrderInfoResponse\x12D\n" +
	"\vCancelOrder\x12\x1c.order.v1.CancelOrderRequest\x1a\x17.order.v1.CheckResponse\x12B\n" +
	"\bGetOrder\x12\x19.order.v1.GetOrderRequest\x1a\x1b.order.v1.OrderInfoResponse\x12B\n" +
	"\n" +
	"ListOrders\x12\x1a.order.v1.ListOrderRequest\x1a\x18.order.v1.ListOrderReplyB\x17Z\x15order/api/order/v1;v1b\x06proto3"

var (
	file_api_service_order_v1_order_proto_rawDescOnce sync.Once
	file_api_service_order_v1_order_proto_rawDescData []byte
)

func file_api_service_order_v1_order_proto_rawDescGZIP() []byte {
	file_api_service_order_v1_order_proto_rawDescOnce.Do(func() {
		file_api_service_order_v1_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_service_order_v1_order_proto_rawDesc), len(file_api_service_order_v1_order_proto_rawDesc)))
	})
	return file_api_service_order_v1_order_proto_rawDescData
}

var file_api_service_order_v1_order_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_service_order_v1_order_proto_goTypes = []any{
	(*CartItem)(nil),           // 0: order.v1.CartItem
	(*OrderRequest)(nil),       // 1: order.v1.OrderRequest
	(*OrderInfoResponse)(nil),  // 2: order.v1.OrderInfoResponse
	(*OrderGoodsInfo)(nil),     // 3: order.v1.OrderGoodsInfo
	(*CancelOrderRequest)(nil), // 4: order.v1.CancelOrderRequest
	(*CheckResponse)(nil),      // 5: order.v1.CheckResponse
	(*GetOrderRequest)(nil),    // 6: order.v1.GetOrderRequest
	(*ListOrderRequest)(nil),   // 7: order.v1.ListOrderRequest
	(*ListOrderReply)(nil),     // 8: order.v1.ListOrderReply
}
var file_api_service_order_v1_order_proto_depIdxs = []int32{
	0, // 0: order.v1.OrderRequest.cartItem:type_name -> order.v1.CartItem
	3, // 1: order.v1.OrderInfoResponse.goods:type_name -> order.v1.OrderGoodsInfo
	2, // 2: order.v1.ListOrderReply.list:type_name -> order.v1.OrderInfoResponse
	1, // 3: order.v1.Order.CreateOrder:input_type -> order.v1.OrderRequest
	4, // 4: order.v1.Order.CancelOrder:input_type -> order.v1.CancelOrderRequest
	6, // 5: order.v1.Order.GetOrder:input_type -> order.v1.GetOrderRequest
	7, // 6: order.v1.Order.ListOrders:input_type -> order.v1.ListOrderRequest
	2, // 7: order.v1.Order.CreateOrder:output_type -> order.v1.OrderInfoResponse
	5, // 8: order.v1.Order.CancelOrder:output_type -> order.v1.CheckResponse
	2, // 9: order.v1.Order.GetOrder:output_type -> order.v1.OrderInfoResponse
	8, // 10: order.v1.Order.ListOrders:output_type -> order.v1.ListOrderReply
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_service_order_v1_order_proto_init() }
func file_api_service_order_v1_order_proto_init() {
	if File_api_service_order_v1_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_service_order_v1_order_proto_rawDesc), len(file_api_service_order_v1_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_service_order_v1_order_proto_goTypes,
		DependencyIndexes: file_api_service_order_v1_order_proto_depIdxs,
		MessageInfos:      file_api_service_order_v1_order_proto_msgTypes,
	}.Build()
	File_api_service_order_v1_order_proto = out.File
	file_api_service_order_v1_order_proto_goTypes = nil
	file_api_service_order_v1_order_proto_depIdxs = nil
}
