#!/usr/bin/env python3
"""Generate demo data for kratos-shop dashboard.

Outputs sql/08_seed_demo.sql with:
- 100 demo users (each with 3~5 paid orders between 2026-01 and 2026-08)
- 50 goods across digital / home appliance / clothing / shoes & bags / furniture
- order_goods / order_address / order_pays rows for dashboard statistics
"""

from __future__ import annotations

import random
from datetime import datetime, timedelta
from pathlib import Path

random.seed(20260813)

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "sql" / "08_seed_demo.sql"

PASSWORD = (
    "$pbkdf2-sha512$781f496fd9233c152837110ac2ce8a79"
    "$0408f25f5393afa7259e9fad0fceb1a2f3e406641d221b0b5562fb9ad46f8406"
)

BRANDS = [
    (1001, "Apple"),
    (1002, "Huawei"),
    (1003, "Xiaomi"),
    (1004, "Lenovo"),
    (1005, "Dell"),
    (1006, "Haier"),
    (1007, "Midea"),
    (1008, "Gree"),
    (1009, "Sony"),
    (1010, "Uniqlo"),
    (1011, "Nike"),
    (1012, "Li-Ning"),
    (1013, "Anta"),
    (1014, "Belle"),
    (1015, "IKEA"),
    (1016, "MUJI"),
]

TYPES = [
    (1001, "数码产品", "DIGITAL"),
    (1002, "家用电器", "APPLIANCE"),
    (1003, "服饰", "CLOTHING"),
    (1004, "鞋包", "SHOES_BAGS"),
    (1005, "家具", "FURNITURE"),
]

CATEGORIES = [
    (1001, "数码"),
    (1002, "家电"),
    (1003, "服装"),
    (1004, "鞋包"),
    (1005, "家具"),
]

# (name, category_id, brand_id, type_id, market_price)
GOODS = [
    # 数码
    ("iPhone 16 Pro 256G", 1001, 1001, 1001, 1299900),
    ("iPhone 16 128G", 1001, 1001, 1001, 799900),
    ("华为 Mate 70 Pro", 1001, 1002, 1001, 899900),
    ("华为 Pura 70", 1001, 1002, 1001, 649900),
    ("小米 15 Pro", 1001, 1003, 1001, 599900),
    ("小米 14", 1001, 1003, 1001, 429900),
    ("MacBook Pro 14 英寸", 1001, 1001, 1001, 1899900),
    ("MacBook Air 13 英寸", 1001, 1001, 1001, 1199900),
    ("ThinkPad X1 Carbon", 1001, 1004, 1001, 1399900),
    ("拯救者 Y9000P", 1001, 1004, 1001, 1099900),
    ("Dell XPS 14", 1001, 1005, 1001, 1499900),
    ("小米笔记本 Pro 16", 1001, 1003, 1001, 799900),
    # 家电
    ("格力 1.5 匹新一级能效空调", 1002, 1008, 1002, 399900),
    ("美的 大 1.5 匹变频空调", 1002, 1007, 1002, 359900),
    ("海尔 1.5 匹静悦空调", 1002, 1006, 1002, 349900),
    ("海尔 10kg 滚筒洗衣机", 1002, 1006, 1002, 299900),
    ("小天鹅 10kg 水魔方洗衣机", 1002, 1007, 1002, 279900),
    ("西门子 8kg 滚筒洗衣机", 1002, 1005, 1002, 459900),
    ("美的 508L 对开门冰箱", 1002, 1007, 1002, 499900),
    ("海尔 501L 全空间保鲜冰箱", 1002, 1006, 1002, 599900),
    ("容声 452L 十字对开门冰箱", 1002, 1007, 1002, 429900),
    ("索尼 65 英寸 4K 电视", 1002, 1009, 1002, 699900),
    ("小米电视 S Pro 75 英寸", 1002, 1003, 1002, 599900),
    ("TCL 85 英寸 Q10G 电视", 1002, 1003, 1002, 1299900),
    # 服装
    ("优衣库 弹力休闲长裤", 1003, 1010, 1003, 29900),
    ("李宁 针织运动长裤", 1003, 1012, 1003, 19900),
    ("Levi's 501 经典牛仔裤", 1003, 1010, 1003, 59900),
    ("无印良品 亚麻直筒长裤", 1003, 1016, 1003, 34900),
    ("优衣库 速干短裤", 1003, 1010, 1003, 19900),
    ("Nike 运动短裤", 1003, 1011, 1003, 24900),
    ("Adidas 训练短裤", 1003, 1011, 1003, 22900),
    ("迪卡侬 户外速干短裤", 1003, 1013, 1003, 9900),
    # 鞋包
    ("Nike Air Force 1", 1004, 1011, 1004, 89900),
    ("Adidas Ultraboost 跑鞋", 1004, 1011, 1004, 129900),
    ("李宁 飞电 4C 跑鞋", 1004, 1012, 1004, 69900),
    ("安踏 氮科技篮球鞋", 1004, 1013, 1004, 59900),
    ("Clarks 商务正装皮鞋", 1004, 1014, 1004, 109900),
    ("百丽 头层牛皮皮鞋", 1004, 1014, 1004, 79900),
    ("红蜻蜓 软底商务皮鞋", 1004, 1014, 1004, 49900),
    ("百丽 细跟高跟鞋", 1004, 1014, 1004, 69900),
    ("达芙妮 简约高跟鞋", 1004, 1014, 1004, 39900),
    ("Staccato 经典高跟鞋", 1004, 1014, 1004, 89900),
    ("Coach 托特包", 1004, 1014, 1004, 299900),
    ("新秀丽 商务双肩包", 1004, 1015, 1004, 69900),
    ("小米 都市商务背包", 1004, 1003, 1004, 19900),
    # 家具
    ("宜家 利蒙书桌", 1005, 1015, 1005, 49900),
    ("北欧实木书桌", 1005, 1015, 1005, 159900),
    ("电竞升降桌 1.4m", 1005, 1015, 1005, 89900),
    ("人体工学椅", 1005, 1015, 1005, 129900),
    ("北欧风餐椅", 1005, 1015, 1005, 39900),
]

ADDRESS_POOL = [
    ("广东省", "深圳市", "南山区", "科技园路 88 号"),
    ("广东省", "广州市", "天河区", "体育西路 200 号"),
    ("上海市", "上海市", "浦东新区", "世纪大道 500 号"),
    ("北京市", "北京市", "朝阳区", "建国路 100 号"),
    ("浙江省", "杭州市", "西湖区", "文三路 66 号"),
    ("江苏省", "南京市", "鼓楼区", "中山北路 88 号"),
    ("四川省", "成都市", "武侯区", "天府大道 1000 号"),
    ("湖北省", "武汉市", "洪山区", "光谷大道 77 号"),
]


def rand_time(start: datetime, end: datetime) -> datetime:
    delta = int((end - start).total_seconds())
    return start + timedelta(seconds=random.randint(0, delta))


def fmt(dt: datetime) -> str:
    return dt.strftime("%Y-%m-%d %H:%M:%S+08")


def esc(value: str) -> str:
    return value.replace("'", "''")


def main() -> None:
    lines: list[str] = []
    add = lines.append

    add("-- ============================================================")
    add("-- Demo seed data generated by scripts/generate_seed_demo.py")
    add("-- 100 users / 50 goods / ~400 orders, 2026-01 ~ 2026-08")
    add("-- ============================================================")

    # ---------------- shop_user ----------------
    add("\\connect shop_user")
    add("BEGIN;")
    add("DELETE FROM user_addresses WHERE user_id BETWEEN 1001 AND 1100;")
    add("DELETE FROM users WHERE id BETWEEN 1001 AND 1100;")
    for uid in range(1001, 1101):
        mobile = f"139{10000000 + uid - 1001:08d}"
        birthday = rand_time(datetime(1975, 1, 1), datetime(2000, 12, 31))
        gender = random.choice(["male", "female"])
        add_time = rand_time(datetime(2025, 11, 1), datetime(2026, 7, 31))
        add(
            f"INSERT INTO users (id, mobile, password, nick_name, birthday, gender, role, add_time, update_time) "
            f"VALUES ({uid}, '{mobile}', '{PASSWORD}', '{esc('演示用户' + str(uid))}', "
            f"'{fmt(birthday)}', '{gender}', 1, '{fmt(add_time)}', '{fmt(add_time)}');"
        )
        province, city, district, street = random.choice(ADDRESS_POOL)
        add(
            f"INSERT INTO user_addresses (user_id, is_default, mobile, name, province, city, districts, address, post_code, add_time, update_time) "
            f"VALUES ({uid}, 1, '{mobile}', '{esc('演示用户' + str(uid))}', '{esc(province)}', '{esc(city)}', '{esc(district)}', '{esc(street)}', '518000', NOW(), NOW());"
        )
    add("SELECT setval('users_id_seq', GREATEST((SELECT MAX(id) FROM users), 1));")
    add("SELECT setval('user_addresses_id_seq', GREATEST((SELECT MAX(id) FROM user_addresses), 1));")
    add("COMMIT;")

    # ---------------- shop_goods ----------------
    add("\\connect shop_goods")
    add("BEGIN;")
    add("DELETE FROM goods_images WHERE goods_id BETWEEN 1001 AND 1050;")
    add("DELETE FROM goods_inventories WHERE sku_id BETWEEN 1001 AND 1050;")
    add("DELETE FROM goods_specification_skus WHERE sku_id BETWEEN 1001 AND 1050;")
    add("DELETE FROM goods_skus WHERE id BETWEEN 1001 AND 1050;")
    add("DELETE FROM goods WHERE id BETWEEN 1001 AND 1050;")
    add("DELETE FROM goods_type_brands WHERE brand_id BETWEEN 1001 AND 1016;")
    add("DELETE FROM goods_category_brands WHERE category_id BETWEEN 1001 AND 1005;")
    add("DELETE FROM goods_types WHERE id BETWEEN 1001 AND 1005;")
    add("DELETE FROM brands WHERE id BETWEEN 1001 AND 1016;")
    add("DELETE FROM categories WHERE id BETWEEN 1001 AND 1005;")

    for bid, name in BRANDS:
        add(
            f"INSERT INTO brands (id, name, logo, \"desc\", is_tab, sort) "
            f"VALUES ({bid}, '{esc(name)}', '', '{esc(name)}', TRUE, {bid - 1000});"
        )
    for cid, name in CATEGORIES:
        add(
            f"INSERT INTO categories (id, name, parent_category_id, level, is_tab, sort) "
            f"VALUES ({cid}, '{esc(name)}', 0, 1, TRUE, {cid - 1000});"
        )
        add(
            f"INSERT INTO goods_category_brands (category_id, brands_id) "
            f"SELECT {cid}, id FROM brands WHERE id BETWEEN 1001 AND 1016;"
        )
    for tid, name, code in TYPES:
        add(
            f"INSERT INTO goods_types (id, name, type_code, name_alias, is_virtual, \"desc\", sort) "
            f"VALUES ({tid}, '{esc(name)}', '{code}', '', FALSE, '', {tid - 1000});"
        )
        add(
            f"INSERT INTO goods_type_brands (brand_id, type_id) "
            f"SELECT id, {tid} FROM brands WHERE id BETWEEN 1001 AND 1016;"
        )

    price_by_goods: dict[int, int] = {}
    sku_name_by_id: dict[int, str] = {}
    for idx, (name, cid, bid, tid, price) in enumerate(GOODS, start=1001):
        gid = idx
        price_by_goods[gid] = price
        sku_name_by_id[gid] = name
        sn = f"DEMO-G-{gid:04d}"
        add(
            f"INSERT INTO goods (id, category_id, brands_id, type_id, name, name_alias, goods_sn, goods_tags, market_price, "
            f"goods_brief, goods_front_image, goods_images, on_sale, ship_free, ship_id, is_new, is_hot, click_num, sold_num, fav_num) "
            f"VALUES ({gid}, {cid}, {bid}, {tid}, '{esc(name)}', '', '{sn}', 'demo', {price}, '演示商品', '', '[]', "
            f"TRUE, {random.choice([True, False])}, 0, {random.choice([True, False])}, {random.choice([True, False])}, "
            f"{random.randint(100, 5000)}, 0, {random.randint(0, 300)});"
        )
        inv = random.randint(50, 500)
        add(
            f"INSERT INTO goods_skus (id, goods_id, goods_sn, goods_name, sku_name, sku_code, bar_code, price, promotion_price, "
            f"points, remarks_info, pic, on_sale, attr_info, inventory) "
            f"VALUES ({gid}, {gid}, '{sn}', '{esc(name)}', '标准版', 'DEMO-SKU-{gid:04d}', 'DEMO-BAR-{gid:04d}', {price}, "
            f"{random.randint(0, int(price * 0.2))}, 0, '', '', TRUE, '', {inv});"
        )
        add(
            f"INSERT INTO goods_inventories (sku_id, inventory) VALUES ({gid}, {inv});"
        )
    add("COMMIT;")

    # ---------------- shop_order ----------------
    add("\\connect shop_order")
    add("BEGIN;")
    add("DELETE FROM order_goods WHERE order_sn LIKE 'DEMO%';")
    add("DELETE FROM order_pays WHERE order_sn LIKE 'DEMO%';")
    add("DELETE FROM order_address WHERE order_sn LIKE 'DEMO%';")
    add("DELETE FROM orders WHERE order_sn LIKE 'DEMO%';")

    oid = 100001
    gid = 1
    sold_by_sku: dict[int, int] = {}
    for uid in range(1001, 1101):
        order_count = random.randint(3, 5)
        for _ in range(order_count):
            if random.random() < 0.35:
                created = rand_time(datetime(2026, 7, 15), datetime(2026, 8, 13, 23, 59))
            else:
                created = rand_time(datetime(2026, 1, 1), datetime(2026, 7, 14, 23, 59))
            updated = created + timedelta(minutes=random.randint(5, 600))
            order_sn = "DEMO" + created.strftime("%Y%m%d%H%M%S") + f"{gid:05d}"
            status = random.choice([2, 2, 2, 3, 3, 4, 4, 6])
            item_count = random.randint(1, 3)
            goods_amount = 0
            item_sql: list[str] = []
            used_skus: set[int] = set()
            for _ in range(item_count):
                sku = random.choice(list(range(1001, 1051)))
                while sku in used_skus:
                    sku = random.choice(list(range(1001, 1051)))
                used_skus.add(sku)
                num = random.randint(1, 3)
                price = price_by_goods[sku]
                total = price * num
                goods_amount += total
                sku_name = sku_name_by_id[sku]
                sold_by_sku[sku] = sold_by_sku.get(sku, 0) + num
                item_sql.append(
                    f"INSERT INTO order_goods (order_sn, user_id, sku_id, sku_name, sku_price, num, total_price) "
                f"VALUES ('{order_sn}', {uid}, {sku}, '{esc(sku_name)} 标准版', {price}, {num}, {total});"
                )
            express = random.choice([0, 0, 1000])
            order_amount = goods_amount + express
            add(
                f"INSERT INTO orders (id, \"user\", order_sn, order_amount, goods_amount, order_status, express_amount, post, created_at, updated_at) "
                f"VALUES ({oid}, {uid}, '{order_sn}', {order_amount}, {goods_amount}, {status}, {express}, '', "
                f"'{fmt(created)}', '{fmt(updated)}');"
            )
            province, city, district, street = random.choice(ADDRESS_POOL)
            mobile = f"139{10000000 + uid - 1001:08d}"
            add(
                f"INSERT INTO order_address (\"user\", order_sn, recipient_name, recipient_mobile, province, city, districts, address, post_code) "
                f"VALUES ({uid}, '{order_sn}', '{esc('演示用户' + str(uid))}', '{mobile}', '{esc(province)}', '{esc(city)}', '{esc(district)}', '{esc(street)}', '518000');"
            )
            add("\n".join(item_sql))
            if status != 5:
                pay_time = created + timedelta(minutes=random.randint(1, 30))
                pay_type = random.choice(["alipay", "wechat"])
                add(
                    f"INSERT INTO order_pays (\"user\", order_sn, trade_no, pay_type, pay_status, pay_time) "
                    f"VALUES ({uid}, '{order_sn}', 'TRADE{order_sn}', '{pay_type}', 2, '{fmt(pay_time)}');"
                )
            oid += 1
            gid += 1

    add("SELECT setval('orders_id_seq', GREATEST((SELECT MAX(id) FROM orders), 1));")
    add("SELECT setval('order_address_id_seq', GREATEST((SELECT MAX(id) FROM order_address), 1));")
    add("SELECT setval('order_goods_id_seq', GREATEST((SELECT MAX(id) FROM order_goods), 1));")
    add("SELECT setval('order_pays_id_seq', GREATEST((SELECT MAX(id) FROM order_pays), 1));")
    add("COMMIT;")

    # ---------------- shop_inventory ----------------
    add("\\connect shop_inventory")
    add("BEGIN;")
    add("DELETE FROM inventories WHERE sku_id BETWEEN 1001 AND 1050;")
    for gid, price in price_by_goods.items():
        add(
            f"INSERT INTO inventories (sku_id, inventory, locked, version) "
            f"VALUES ({gid}, {random.randint(50, 500)}, 0, 0);"
        )
    add("SELECT setval('inventories_id_seq', GREATEST((SELECT MAX(id) FROM inventories), 1));")
    add("COMMIT;")

    # ---------------- update sold_num ----------------
    add("\\connect shop_goods")
    for sku, num in sold_by_sku.items():
        add(f"UPDATE goods SET sold_num = {num} WHERE id = {sku};")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"generated {OUT} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
