// Code generated by Wire. DO NOT EDIT.

//go:build !wireinject
// +build !wireinject

package main

import (
	"inventory/internal/biz"
	"inventory/internal/conf"
	"inventory/internal/data"
	"inventory/internal/server"
	"inventory/internal/service"

	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

func initApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, mq *conf.Mq, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData)
	client := data.NewRedis(confData)
	dataData, cleanup, err := data.NewData(confData, logger, db, client)
	if err != nil {
		return nil, nil, err
	}
	inventoryRepo := data.NewInventoryRepo(dataData, logger)
	inventoryUsecase := biz.NewInventoryUsecase(inventoryRepo, logger)
	inventoryService := service.NewInventoryService(inventoryUsecase, mq, logger)
	grpcServer := server.NewGRPCServer(confServer, inventoryService, logger)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, grpcServer, registrar)
	return app, cleanup, nil
}
